"""Grade B review: curated entries of the perk group (1009, 770, 85) and the combat group (2179, 1384, 1112)."""

MODS = {}

MODS["1009"] = dict(
    name="Perkaholic - PTF updated (1.9.4-1.9.8)", author="Xylozi (original); DarkDevil428 (PTF)", version="1.1.9", subcat="perks",
    status="Lido por inteiro; nada executado (a pasta extraída de 2024 já foi descartada em Reviewed_Mods)",
    purpose="Acrescentar perks às listas existentes e perks novas para Arco, Armas de Haste e Briga: 56 no total. (Página do mod.)",
    observed=[
        "6 patches com sufixo `perkaholic` em `Libs/Tables/rpg`: `perk` (56 novas, 1 alterada), `buff` (56 novos, 5 alterados), `perk_buff` (55 ligações), `perk_buff_override` (17), `perk2perk_exclusivity` (3) e `skill` (1 alterada). Nenhuma tabela é substituída. ^c",
        "13 pacotes de idioma (`<Idioma>_xml.pak`), cada um com 10 textos alterados e 114 novos. ^c",
        "Cada perk nova tem um buff `Cpp:Constant` com a fórmula em `params` (ex.: `wat*1.05` = 'você causa 5 % mais dano'). Níveis 3 a 14, nas habilidades Briga (24), Arco (18), Machado (17), Maça (21), Armas de Haste (23), Defesa (15) e Esgrima (2), e em dois atributos (seletores 1 e 3). ^c",
        "Muda a perk `Like a feather` (nível 4 → 5, renomeada `Featherweight I`) e torna a habilidade 23 (Armas de Haste) visível (`hidden` True → False). ^c"],
    loads="O manifest lista 1.9.4 a 1.9.9 (inclui o 1.9.8); o sufixo é igual ao id derivado (`perkaholic`). ^c",
    systems=["Perks e seleção de perks por habilidade e atributo.", "Buffs permanentes de combate (dano, vigor, defesa, chance de nocaute, sangramento, veneno).", "Exclusividade entre perks.", "Visibilidade da habilidade Armas de Haste."],
    newcontent=["56 perks e 56 buffs (catálogo completo na seção de balanceamento B15).", "3 pares de perks exclusivas (Serration x Poisoner, Yokel x Townsman, Unstoppable Force x Immovable Object)."],
    stats=["Fórmulas de `buff.params` entre 2,5 % e 25 %; só Fury Swipes (`asp*2`) e Diehard (`ibi*2`) dobram algo.", "Perks de nível 3 a 14 em 7 habilidades e 2 atributos."],
    text=["114 textos novos e 10 alterados por idioma, em 13 idiomas."],
    assets=["Nenhum arquivo visual; os ícones são os do jogo (`icon_id` por nome, ex.: `dodger`)."],
    params=["`perk.level`, `perk.skill_selector`, `buff.params`, `perk_buff_override` (cadeias de nível)."],
    balance=["B15"],
    snippets=[("Duas perks do catálogo", "Martial Artist [Briga, nível 3]   buff: hlh*0.95, slh*0.95   'Golpes machucam 5 % menos'\nHard Hitter    [Briga, nível 9]   buff: wat*1.05            'Você causa 5 % mais dano'\nFury Swipes    [Armas de Haste, nível 9]  buff: asp*2   'Quando muito cercado, bate até 2x mais rápido'",
               "`hlh`/`slh` são o dano que a vida e o vigor sofrem, `wat` é o dano da arma, `asp` a velocidade do golpe. Os números são pequenos (5 %) exceto Fury Swipes (e Diehard, `ibi*2`), que dobram algo. Cada perk é uma escolha que o jogador faz ao subir de nível a habilidade. ^c")],
    deps=["Nenhuma de arquivo. Em jogo as perks de 'Armas de Haste' só têm efeito se o jogador usar armas dessa classe."],
    file_overlap=["Mesmas tabelas e mesmas perks que 85 (192 linhas em comum) e 770 (186)."],
    func_overlap=["Redundante com 770 e 85. Em `skill` (habilidade 23 visível) coincide com 2045."],
    conflicts=["Com 85/770: só uma versão pode valer (175 e 171 de 192 e 186 linhas idênticas; o resto difere em colunas de interface e em `mst*1.1`). Com 2179: 2 linhas."],
    errors=["As linhas de `perk` trazem os atributos `autolearnable` e `exclude_in_game_mode`, mas o cabeçalho do patch não os declara; o motor pode ignorá-los (ficam como o jogo) ^n.", "Perk `Featherweight III` tem `perk_buff` vazio (a cadeia I-II-III usa `perk_buff_override`): coerente, não é erro ^d."],
    unique=["Única versão com sufixo e manifest que carrega no 1.9.8, com `mst*1.1` correto em Proficiency e com 13 idiomas."],
    keep=["O catálogo de 56 perks como lista de candidatas a `krs_perks` (decisão aberta: exigir o Perkaholic ou copiar partes). A estrutura de cadeias (`perk_buff_override`) é a melhor referência de como fazer perks em níveis."],
    reject=["Nada, enquanto a decisão exigir-ou-copiar estiver aberta."],
    questions=["Exigir o Perkaholic (OBJECTIVES.md) ou copiar perks escolhidas? Se copiar, quais das 56?"],
    rank_note="1º de 3 em Perks: a linha Perkaholic",
    action="Referência da linha. Manter o `.rar` (o mod ainda é candidato); os outros dois são redundantes.",
    verdict="ok", verdict_text="Candidato",
)

MODS["770"] = dict(
    name="Perkaholic updated (v1.07)", author="Xylosi (original); atualização por terceiro", version="1.07 (2019)", subcat="perks",
    status="Lido por inteiro; nada executado. Está em quarentena (_quarantine)",
    purpose="Atualizar o Perkaholic para o jogo 1.9.*. (Página do mod.)",
    observed=[
        "5 tabelas inteiras (`buff`, `perk`, `perk_buff`, `perk_buff_override`, `perk2perk_exclusivity`), sem sufixo: substituem as tabelas do jogo. As mesmas 56 perks e 56 buffs do 85 e do 1009. ^c",
        "O pak guarda os arquivos com caminhos como `../../../Data/Libs/Tables/rpg/perk.tbl` (sobem para fora do pak, e usam `.tbl`) ao lado dos `.xml`: padrão que a verificação de segurança marca. ^c",
        "Um único texto em inglês (78 alterados e 134 novos). ^c",
        "Ao contrário do 85, o manifest não lista versões do jogo. ^c"],
    loads="Sem restrição no manifest; mas as tabelas inteiras refletem o jogo de 2019 e desfazem o 1.9.7/1.9.8 nessas cinco tabelas. ^d",
    systems=["Perks, buffs e exclusividade."],
    newcontent=["As mesmas 56 perks e 56 buffs."],
    stats=["Mesmas fórmulas do 85 (189 células iguais). Diferença do 1009: `rst*1.1` em Proficiency."],
    text=["Só inglês: 78 textos alterados e 134 novos."], assets=["Nenhum."],
    params=["Igual ao 85."],
    balance=["B15"],
    snippets=[("Caminhos dentro do pak", "../../../Data/Libs/Tables/rpg/perk.tbl\n../../../Data/Libs/Tables/rpg/buff.tbl\n...",
               "Caminho relativo que sobe três pastas. O jogo lê o pak como um sistema de arquivos virtual: este padrão é inútil para o jogo (os `.xml` ao lado é que são lidos) e é exatamente o que a verificação marca como risco de travessia de caminho. Parece resto de empacotamento de 2019, não má-fé, mas por isso o arquivo está em quarentena. ^d")],
    deps=["Nenhuma."],
    file_overlap=["Mesmas 5 tabelas que 85 e 1009."],
    func_overlap=["Redundante com 85 e 1009."],
    conflicts=["Com 85 e 1009: as mesmas perks; só um deles."],
    errors=["Tabelas inteiras ^c.", "Caminhos `../` no pak ^c.", "`rst*1.1` em Proficiency ^c (código que não é de vigor máximo)."],
    unique=["Nada que o 1009 não tenha."],
    keep=["Nada."],
    reject=["O arquivo inteiro: redundante, sem sufixo e com o padrão de caminho."],
    questions=["Nenhuma."],
    rank_note="2º de 3 em Perks: a linha Perkaholic",
    action="Manter na quarentena e marcar como redundante. Não migrar para Reviewed_Mods antes do autor decidir.",
    verdict="bad", verdict_text="Rejeitar",
)

MODS["85"] = dict(
    name="Perkaholic (v1.05)", author="Xylozi", version="1.04 no manifest (arquivo 1.05)", subcat="perks",
    status="Lido por inteiro; nada executado",
    purpose="Acrescentar perks às listas existentes e perks novas para Arco, Armas de Haste e Briga. (Página do mod.)",
    observed=[
        "O manifest só lista as versões do jogo `1.3` e `1.3.1`: o motor desativa o mod no 1.9.8. ^c",
        "6 tabelas inteiras sem sufixo: `buff`, `perk`, `perk2perk_exclusivity`, `perk_buff`, `perk_buff_override` e `skill`. Elas substituem as tabelas do jogo e regravam coisas que não são do mod: 63 buffs do jogo (mudanças de UI, de classe e de exclusividade, ex.: `alpha_male` classe 18 → 1) e 19 descrições de habilidade. ^c",
        "O cabeçalho de `perk.xml` não declara `autolearnable` nem `exclude_in_game_mode` (colunas que o jogo tem hoje): pela regra 5 elas ficam vazias nas 541 perks da tabela. ^n",
        "Só inglês: 226 textos alterados e 685 novos. ^c"],
    loads="NÃO carrega no 1.9.8 como empacotado (o manifest lista só 1.3/1.3.1). Editar a linha mudaria isso, mas as tabelas inteiras ainda trariam o jogo de 2018. A versão declarada não foi usada como prova de compatibilidade; a prova é o conteúdo das tabelas. ^c",
    systems=["Perks, buffs, habilidades (descrições) e exclusividade, além de regravar buffs do jogo que não são perks novas."],
    newcontent=["As mesmas 56 perks e 56 buffs do 1009."],
    stats=["Mesmas fórmulas; mais 105 células de 'mudança' em buffs e habilidades do jogo (valores de 2018)."],
    text=["226 textos alterados e 685 novos (inglês)."], assets=["Nenhum."],
    params=["Igual ao 1009."],
    balance=["B15"],
    snippets=[("O que o 85 regrava além das perks", "buff alpha_male [0d635e3e]\n  buff_ai_tag_id   10 → (vazio)\n  buff_class_id    18 → 1\n  buff_exclusivity_id  3 → 1",
               "Isto não tem relação com perks novas: é um buff do jogo (a perk 'alpha male') que a tabela inteira de 2018 devolve ao estado antigo. Em 63 buffs e 19 habilidades o mod 'espalha' mudanças para fora do seu escopo, sem querer: é a razão principal para não usar a tabela inteira. ^c")],
    deps=["Nenhuma."],
    file_overlap=["Mesmas tabelas que 770 e 1009."],
    func_overlap=["Redundante com 1009 e 770."],
    conflicts=["Com 2179: 12 linhas de buff e exclusividade (o 85 desfaz o que o 2179 ajusta). Com 1009/770: mesmas perks."],
    errors=["Manifest só 1.3/1.3.1 ^c.", "Tabelas inteiras com valores de 2018 ^c.", "Cabeçalho incompleto de `perk` ^n.", "`rst*1.1` em Proficiency ^c."],
    unique=["Nada."],
    keep=["Nada."],
    reject=["O arquivo inteiro."],
    questions=["Q6 só se por algum motivo se quiser usá-lo."],
    rank_note="3º de 3 em Perks: a linha Perkaholic",
    action="Descartar (redundante e desatualizado). Registrar o achado das mudanças em buffs do jogo como exemplo de 'vazamento' de escopo.",
    verdict="bad", verdict_text="Rejeitar",
)

MODS["2179"] = dict(
    name="True Hardcore Combat (PTF)", author="Nfrog2swamp1", version="1.0 (v1.3 do arquivo)", subcat="combat", family="True Hardcore",
    status="Lido por inteiro; nada executado",
    purpose="'Torna o combate mais realista, agressivo e centrado em combos. Melhora o arco com arcos e flechas mais rápidos, mas pune mais quando você é fraco.' (Página do mod.)",
    observed=[
        "11 patches com sufixo `truehardcorecombat` (igual ao `<modid>`): `ammo`, `food`, `pickable_item`, `buff`, `morale_change`, `perk2perk_exclusivity`, `perk_rpg_param_override`, `rpg_movement_type`, `rpg_param`, `social_class`, `soul_archetype`. Cada `.xml` vem com um `.tbl` binário ao lado. ^c",
        "`rpg_param`: 71 linhas novas (constantes ocultas de combate, arco, moral, vigor) e 16 alteradas. ^c",
        "`buff`: 35 buffs de perks e poções alterados (durações de poção 600 → 120/300 s; perks de dano e de bloqueio reduzidas). 36 textos do inglês foram alterados para os novos números. ^c",
        "`social_class` (42 linhas) e `soul_archetype` (5): a vida e o estado do equipamento com que os NPCs nascem (`preset_items_health_base`/`_random`), armadura básica do corpo e ataque desarmado. ^c",
        "`rpg_movement_type` (3): peso da armadura sobre velocidade e regeneração de vigor. `morale_change` (7): a moral que cada evento dá é cortada pela metade. ^c",
        "`ammo` (14) e `pickable_item` (13): potência, dano e modelo de flechas; preços de 5 itens. `food` (6): 6 itens de comida/poção. ^c"],
    loads="O manifest não lista versões. Sufixo igual ao id. Nenhum cabeçalho fora do padrão. As 71 chaves novas incluem `UnarmedHitArmorDamageCoef`, que nenhuma lista de constantes lida conhece (Q12). ^c",
    systems=["IA de combate (ritmo, bloqueio, truques, combos).", "Dano máximo, vigor e regeneração.", "Perks e buffs de combate; poções.", "Equipamento e moral dos NPCs.", "Arco e flechas (dispersão, zoom, carga, dano).", "Peso da armadura e velocidade."],
    newcontent=["Nenhum item ou perk novo; 71 constantes `rpg_param` novas e 1 exclusividade de perk (Serration x Heavy tip)."],
    stats=["Ver B5 (IA), B6 (pesos de bloqueio), B8 (dano e vigor), B9 (habilidade), B10 (NPCs), B11 (perks e poções) e B12 (arco)."],
    text=["36 textos alterados (descrições de perks e poções) para casar com os novos valores."],
    assets=["Nenhum visual. 8 trocas de modelo de aljava e 12 de modelo de flecha (só nomes de arquivo do jogo)."],
    params=["`MaxDamage` 200 → 100; `CombatAutoMaxAttackDelay` 6 → 3; `CombatAutoSPBWeight` 1,5 → 0,2; `CombatAutoPBWeight` 2,5 → 1,8; `MaxPerfectBlockSlotModifier` 0,85 → 0,6; `MaxSpecialPerfectBlockSlotModifier` 0,6 → 0,2; `SkillToDefense` 0,02857 → 0,2857; `AimSpreadMax` 15 → 12."],
    balance=["B5", "B6", "B8", "B9", "B10", "B11", "B12"],
    snippets=[("Texto e valor mudam juntos", "perk_weapon_cruncher_desc\n  jogo  'If you beat your opponent in a clinch, you'll damage his weapon 15% more ...'\n+ mod   '... damage his weapon 5% more ...'\n(buff perk_weapon_cruncher  cdw+0.15 → cdw+0.05)",
               "O mod muda o número no buff e também o texto da descrição, de modo que o jogador lê o valor certo. Isto o distingue do 1384, que muda 8 buffs sem atualizar os textos. ^c"),
              ("Parâmetro oculto de IA", "CombatAutoMaxAttackDelay   jogo 6   → 2179: 3   1112/1384: 0,01\nCombatAutoSPBWeight        jogo 1,5 → 2179: 0,2   1384: 1   1558: 0,5",
               "A IA espera até este tempo (segundos) entre um ataque e outro. 6 é o valor do jogo; 3 deixa o inimigo mais agressivo; 0,01 o faz atacar sem pausa. O 2179 é o mais moderado dos que mexem nisso. ^c")],
    deps=["Nenhuma de arquivo. Várias constantes novas (`CombatAuto*`) só existem como valores lidos no 1.9.6; não se sabe se o 1.9.8 as lê igual (Q12)."],
    file_overlap=["Mesmas tabelas `rpg_param` e `perk_rpg_param_override` que 1112, 1384, 1558, 2173; `buff` com 1384/2173/85/1009; `ammo` com 2035; `food` com 2011/2345."],
    func_overlap=["Concorre com 1112, 1384 e 1558 na IA e no vigor; com 2035 na flecha; com 2173 em perk de manutenção."],
    conflicts=["Linhas em comum e em conflito: com 1112, 27 de 31; com 1384, 24 de 29; com 1558, 18 de 21; com 2035, 17 de 25 (as 24 células de flecha comuns são todas diferentes); com 2011, 6 de 6 em `food`/`buff`/`pickable_item`."],
    errors=["`.tbl` binário ao lado de cada `.xml` (qual vale?) ^n.", "`UnarmedHitArmorDamageCoef` desconhecida ^n.", "Células em branco no lugar de 0 em 6 linhas de `food` (decaimento 0 → vazio, saúde 0 → vazio): provavelmente o mesmo valor ^d."],
    unique=["Moral, equipamento dos NPCs, movimento e arco: não aparecem em nenhum outro mod do grupo.", "Atualização dos textos das perks."],
    keep=["A família de ajustes de equipamento e moral dos NPCs (B10) e a atualização dos textos, quando os números forem decididos.", "Os valores de IA, como uma opção moderada entre o jogo e o 1384/1112."],
    reject=["Nada ainda; os valores extremos (`CombatAutoSPBWeight` 0,2, `SkillToDefense` x10) são decisões a rever."],
    questions=["Q1 (`.tbl` ou `.xml`), Q12 (chave desconhecida), Q13 (modo normal ou Hardcore)."],
    rank_note="1º de 3 em Combate: ritmo da IA, bloqueio e vigor",
    action="Referência principal do grupo de combate: estudar parâmetro a parâmetro com o 1384 e o 1112 na revisão final. Não copiar o arquivo inteiro: escolher quais famílias de valores interessam.",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["1384"] = dict(
    name="Modified Combat Overhaul - Directional Combat (BCAIC Lite)", author="não informado no arquivo (sufixo BCAIC)", version="2 (2022)", subcat="combat",
    status="Lido por inteiro; nada executado",
    purpose="'Golpes Mestres exigem correspondência de direção, Bloqueios Perfeitos exigem correspondência de lado, para o jogador e a IA.' (Página do mod.)",
    observed=[
        "Só o pak `zzz_BCAIC_BetterCombatLite.pak`, sem `mod.manifest` (instalação antiga: pak solto em `Data`). Quatro patches com sufixo `BCAIC`: `combat_action_perfect_block` (150 linhas novas), `buff` (8 alteradas), `perk_rpg_param_override` (5) e `rpg_param` (10 novas, 8 alteradas, 3 iguais). ^c",
        "As 150 linhas de bloqueio perfeito acrescentam combinações de zona (zona de ataque x zona de bloqueio x armas) que a tabela do jogo não tem. 130 são idênticas às do 1112. ^c",
        "Os 8 buffs são perks de combate reduzidas (ex.: `wat*1.1` → `wat*1.05`, `cli+0.4` → `cli+0.1`), sem atualizar os textos das perks. ^c"],
    loads="Sem manifest: é instalação 'legada' (pak solto na pasta Data). Se o motor aplica patches PTF de pak solto sem manifest não foi medido nesta passada. ^n",
    systems=["Bloqueio perfeito e golpe mestre (sincronia por direção).", "IA de combate (atraso, pesos de bloqueio, esquiva).", "Perks de combate reduzidas.", "Dano máximo e coeficiente de dano por habilidade."],
    newcontent=["150 linhas novas de bloqueio perfeito."],
    stats=["`CombatAutoMaxAttackDelay` 6 → 0,01; `CombatAutoDodgeWeight` 1,1 → 4; `CombatAutoPBWeight` 2,5 → 2; `CombatAutoSPBWeight` 1,5 → 1; `MaxDamage` 200 → 100; `SkillToDmgConstA` 250 → 700."],
    text=["Nenhuma alteração de texto."], assets=["Nenhum."],
    params=["`CombatAuto*`, `MaxDamage`, `SkillToDmgConstA`, `ArmorStatusToDefenseCoef`, `AverageArmorDefenseWeight`."],
    balance=["B5", "B6", "B7", "B8", "B9", "B11"],
    snippets=[("Perks reduzidas sem texto atualizado", "perk_chain_strike   wat*1.1  → wat*1.05\nperk_furious        wat*1.2  → wat*1.1\nperk_clinch_master  cli+0.4  → cli+0.1\nperk_headcracker    hko+0.1  → hko+0.05",
               "O dano de uma perk como Furious cai de 20 % para 10 % e o poder de nocaute de Headcracker de 10 % para 5 %. Os textos em inglês continuam dizendo os valores antigos: o jogador é induzido ao erro. ^c")],
    deps=["Nenhuma."],
    file_overlap=["Mesmas tabelas que 1112 (141 linhas), 2179 (29), 1558 (14), 2173; `buff` com 85 e 1009 (4 e 1 linhas)."],
    func_overlap=["Quase o mesmo mod que o 1112 (bloqueio por direção); concorre com 2179 e 1558 em parâmetros globais."],
    conflicts=["Com 1112: 141 linhas em comum, só 7 em conflito (de 11 não-bloqueio); com 2179: 24 de 29 em conflito; com 1558: 13 de 14."],
    errors=["Sem manifest ^c.", "Textos de perks não atualizados após reduzir os buffs ^c.", "`CombatAutoMaxAttackDelay` 0,01: valor extremo, deve ser testado ^d."],
    unique=["Nada que o 1112 não tenha, exceto os 8 buffs e as perks reduzidas."],
    keep=["As 150 linhas de bloqueio perfeito por direção (a base técnica do 'combate direcional'), como ponto de partida junto com o 1112.", "A redução das perks, como valor de comparação, depois de atualizar os textos."],
    reject=["`CombatAutoMaxAttackDelay` 0,01 e `CombatAutoDodgeWeight` 4 até testar."],
    questions=["Q7 (ritmo da IA)."],
    rank_note="2º de 3 em Combate: ritmo da IA, bloqueio e vigor",
    action="Estudar o conjunto de linhas de bloqueio perfeito junto com o 1112 (130 de 150 idênticas); escolher uma versão. Textos devem ser atualizados se as perks forem usadas.",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["1112"] = dict(
    name="Combat Overhaul (directional combat)", author="machinegod420", version="1.2 (arquivo 1.6.4, 2020)", subcat="combat",
    status="Lido por inteiro; nada executado",
    purpose="'Faz o combate direcional valer.' (Página do mod.)",
    observed=[
        "5 patches com sufixo `combatoverhaul` (igual ao nome do mod): `combat_action_perfect_block` (156 linhas novas, 12 iguais), `combat_attack_type` (1), `perk_rpg_param_override` (41 novas, 2 alteradas), `rpg_param` (29 novas, 13 alteradas) e `soul` (1). ^c",
        "A maioria dos 41 overrides de `perk_rpg_param_override` repete os mesmos parâmetros no modo Hardcore ('Hardcore Mode - Constants'). ^c",
        "Uma linha de `soul` altera a alma `rat_bernard` (nível de combate 3 → 6): um NPC específico, sem relação com o resto do mod. ^c",
        "`combat_attack_type` muda o custo relativo de vigor do tipo de ataque 5 de 1 para 1,6. ^c"],
    loads="O manifest não lista versões; id derivado `combatoverhaul` = sufixo. ^c",
    systems=["Bloqueio perfeito por direção.", "IA de combate.", "Economia de vigor e dano máximo.", "Custo de ataque por tipo.", "Um NPC (Bernard)."],
    newcontent=["156 linhas de bloqueio perfeito; 29 constantes novas de `rpg_param`."],
    stats=["`CombatAutoMaxAttackDelay` 6 → 0,01; `CombatAutoNoDefenseWeight` 0,4 → 0; `CombatAutoPBWeight` 2,5 → 3,85; `CombatAutoNormalBWeight` 2,8 → 3,475; `BaseAttackStaminaCost` 12 → 22; `StamRegenBase` 22 → 16; `StamRegenFromVit` 1 → 0,1; `MaxDamage` 200 → 100."],
    text=["Nenhum."], assets=["Nenhum."],
    params=["`BaseAttackStaminaCost`, `StamRegen*`, `MaxStatToAttack*`, `CombatAuto*`, `AttackSpeed*`."],
    balance=["B5", "B6", "B7", "B8"],
    snippets=[("Hardcore repete o valor global", "rpg_param                  BaseAttackStaminaCost      12 → 22\nperk_rpg_param_override    Hardcore Mode - Constants / BaseAttackStaminaCost  (novo) 22",
               "Dois patches para a mesma constante: o `rpg_param` vale no modo normal e o override vale no Hardcore (medido para outro parâmetro em ptf-rules). O mod cobre os dois modos com o mesmo número. ^d")],
    deps=["Nenhuma."],
    file_overlap=["Mesmas tabelas que 1384 (141 linhas), 2179 (31), 1558 (14) e 2173."],
    func_overlap=["Quase igual ao 1384, com valores de IA e de vigor próprios; concorre com 2179 e 1558."],
    conflicts=["Com 1384: 7 de 141 linhas em conflito (as outras idênticas); com 2179: 27 de 31; com 1558: 13 de 14."],
    errors=["Alteração de `rat_bernard` sem relação ^c.", "Valores extremos: `StamRegenFromVit` x0,1, `CombatAutoMaxAttackDelay` 0,01 ^d."],
    unique=["Overrides do modo Hardcore completos.", "Constantes de velocidade de ataque (`AttackSpeed*`) e de moral das zonas."],
    keep=["As constantes `AttackSpeedNormal*`/`MaxAttackSpeedMod`/`BigZoneDistanceSlotMod` como candidatas (ninguém mais as define), depois de testar."],
    reject=["A alteração de `rat_bernard`."],
    questions=["Q7 (ritmo da IA); por que o NPC Bernard?"],
    rank_note="3º de 3 em Combate: ritmo da IA, bloqueio e vigor",
    action="Tratar junto com o 1384 (mesma base de bloqueio). Escolher uma só das duas fontes das linhas de bloqueio perfeito.",
    verdict="warn", verdict_text="Investigar / decidir",
)
