"""Grade B review: curated entries of the food group (1483, 1639, 2011, 2345). See grade_b_data_core.py for the markup."""

MODS = {}

MODS["1483"] = dict(
    name="TSM Slower Food Spoil", author="theskymoves", version="1.0 (30/12/2022)", subcat="food",
    status="Lido por inteiro; nada executado",
    purpose="Estender a validade de todos os alimentos 2 vezes (recomendado), 3 ou 5 vezes. (Leia-me do autor.)",
    observed=[
        "Três pastas independentes (`SlowerFoodSpoil_2X`, `_3X`, `_5X`), cada uma com `mod.manifest` e um pak com `food__slowerfoodspoil.xml`. As três têm o mesmo nome de mod: só uma pode ser instalada (o leia-me avisa). ^c",
        "Cada patch tem 111 linhas completas da tabela `food` e muda uma única coluna, `decay_time_hours`: valor do jogo vezes 2, 3 ou 5, sem exceção nas 333 células lidas. ^c",
        "As 111 linhas são exatamente os itens perecíveis: das 202 linhas de `food`, 91 têm decaimento 0 (não estragam) e ficam de fora. ^c",
        "Nenhum texto, script, ícone ou arquivo fora de `Libs/Tables/item`. ^c"],
    loads="O manifest não lista versões (o motor carrega em qualquer uma) e o id derivado do nome, `slowerfoodspoil`, é igual ao sufixo das tabelas. A versão declarada não foi usada como prova. ^c",
    systems=["Alimentação: tempo até a comida estragar (`food.decay_time_hours`)."],
    newcontent=["Nenhum."],
    stats=["`decay_time_hours` x2, x3 ou x5 em 111 alimentos (ex.: carne defumada de coelho 120 h → 240 / 360 / 600 h; lebre cozida 24 h → 48 / 72 / 120 h)."],
    text=["Nenhuma mudança de texto."], assets=["Nenhum."],
    params=["`food.decay_time_hours` (a única coluna alterada)."],
    balance=["B1"],
    snippets=[("Uma linha de `food` nas três opções (só a coluna alterada)",
               "Smoked Rabbit meat [025f546b]  decay_time_hours\n  jogo  120\n+ 2X    240\n+ 3X    360\n+ 5X    600",
               "A coluna é o tempo, em horas de jogo, até o alimento estragar. 120 h são 5 dias: o 2X leva a 10 dias, o 5X a 25 dias. Todas as outras colunas da linha são cópias do jogo (linha completa, como pede a regra 5). ^c")],
    deps=["Nenhuma dependência real. O leia-me cita a DLC 'From the Ashes' com um 'probably?': é só uma tabela do jogo base."],
    file_overlap=["Mesma tabela (`food`) que 1639, 2011 e 2345; arquivo diferente em cada um (os patches têm sufixos diferentes)."],
    func_overlap=["Faz o mesmo que o 1639 (2X) e concorre com o 2011 e o 2345 no apodrecimento."],
    conflicts=["Com 2011 e 2345: mesmas linhas, valores diferentes (68 e 24 células). Quem carrega por último vence a linha inteira (regra 6)."],
    errors=["Nenhum erro estrutural encontrado: sufixo igual ao id, linhas completas, cabeçalho igual ao do jogo. ^c"],
    unique=["Único com três intensidades à escolha do jogador."],
    keep=["O método (multiplicador uniforme sobre os perecíveis) como linha de base e como teste de qualquer valor próprio. Decidir o multiplicador na revisão final."],
    reject=["Nada. O 5X é uma decisão de balanceamento (carne defumada duraria 25 dias), não um defeito."],
    questions=["2X (recomendado pelo autor), 3X ou valores seletivos por tipo de alimento?"],
    rank_note="1º de 4 em Comida, bebida e apodrecimento",
    action="Candidato principal para a parte de apodrecimento. Usar como referência; decidir o multiplicador (ponto de partida: 2X do autor) na revisão final.",
    verdict="ok", verdict_text="Candidato",
)

MODS["1639"] = dict(
    name="Alternate Food Spoil (2X)", author="AlbinEros", version="1.0", subcat="food",
    status="Lido por inteiro; nada executado",
    purpose="Dobrar o tempo que a comida leva para estragar. (Descrição da página.)",
    observed=[
        "Um pak com `food__AlternateFoodSpoil2X.xml`: 202 linhas completas de `food`, das quais 111 mudam e 91 são cópias idênticas do jogo. ^c",
        "Muda só `decay_time_hours`, x2 em 110 linhas. Na linha da Dead Chicken (frango morto) o valor passa de 24 para **2400** (100x em vez de 2x). ^c",
        "Traz também um `food.tbl` de 0 byte no mesmo caminho da tabela do jogo. ^c",
        "O nome do mod (`AlternateFoodSpoil2X`) não tem `<modid>`: o motor deriva o id do nome, o que dá um id com dígito e letras maiúsculas. ^c"],
    loads="O manifest não lista versões. O id derivado tem dígito: pela regra 4 (medida), um id com algo além de letras minúsculas e sublinhado fez o patch não aplicar. É provável que este patch seja ignorado como empacotado. ^d",
    systems=["Alimentação: tempo até estragar."],
    newcontent=["Nenhum."],
    stats=["`decay_time_hours` x2 em 110 de 111 linhas; Dead Chicken 24 h → 2400 h (erro)."],
    text=["Nenhuma."], assets=["Nenhum."],
    params=["`food.decay_time_hours`."],
    balance=["B1"],
    snippets=[("A linha com erro", "Dead Chicken [18ff9093]  decay_time_hours\n  jogo   24\n  1483   48   (2X)\n+ 1639   2400",
               "Todas as outras 110 linhas dobram. Esta passa a 2400 horas (100 dias): quase certamente um zero a mais (era para ser 48). Se o patch fosse aplicado, o frango morto não estragaria na prática. ^c")],
    deps=["Nenhuma."],
    file_overlap=["Mesma tabela e mesmas 111 linhas que o 1483; também 2011 e 2345."],
    func_overlap=["Redundante com o 1483 (2X)."],
    conflicts=["Com 1483: mesmas células (110 iguais, 1 diferente). Com 2011 e 2345: valores diferentes."],
    errors=["Dead Chicken 24 → 2400 (100x) ^c.", "Id derivado com dígito e maiúsculas: patch provavelmente ignorado ^d.", "`food.tbl` vazio (efeito desconhecido) ^n.", "Linhas idênticas ao jogo (91): ruído sem efeito, a regra 7 as conta como iguais. ^c"],
    unique=["Nada que o 1483 não faça."],
    keep=["Nada: tudo o que faz o 1483 faz sem erro."],
    reject=["O arquivo inteiro como está (id inválido, linha com erro, `.tbl` vazio)."],
    questions=["Q2 e Q3: o `.tbl` vazio e o id com dígito atrapalham? (Só vale confirmar se algum dia o 1483 for descartado.)"],
    rank_note="4º de 4 em Comida, bebida e apodrecimento",
    action="Descartar em favor do 1483. Registrar o erro da Dead Chicken como exemplo de erro de digitação.",
    verdict="bad", verdict_text="Rejeitar",
)

MODS["2011"] = dict(
    name="Chefs Kiss (DDDB)", author="Diaz Dizazter (diaz_dizazter)", version="3.7 (21/06/2026)", subcat="food",
    status="Lido por inteiro; nada executado",
    purpose="'Novas regras para comida, bebida, poções, venenos, regeneração de saúde e vigor, buffs de arma e atributo, nutrição, energia e inanição.' (Página do mod.)",
    observed=[
        "7 patches de tabela com sufixo `dddb_chefs_kiss` (igual ao `<modid>`): `food`, `consumable_item`, `item`, `pickable_item`, `potion`, `buff` e `buff_class`. ^c",
        "**Cria um sistema novo de buffs de lanche**: 9 classes de buff novas (Combat Snack, Healing Snack, Fruit Snack, Drink, Healthy Snack, Energy Snack, Vegetable Snack, Heated Snack, Snacky Snack) e 42 buffs novos; 38 linhas de `consumable_item` ligam alimentos (maçã, pera, cenoura, ovos, queijo, salame...) a esses buffs. ^c",
        "Reescreve 180 linhas de `food`: `health_benefit` (165 linhas), `refresh_benefit` (174), `nutrition_benefit` (170), `decay_time_hours` (71), `max_status` (49), e 7 mudanças de tipo/subtipo. ^c",
        "Muda também itens que não são comida do dia a dia: poções, itens de teste e de missão (ex.: 'Generic potion', 'crystal meth', 'charl_horndust', 'OintmentForMarta', 'Test Potion: Invincible', 'Abortion potion'). ^c",
        "Troca 94 textos do jogo e acrescenta 44 (os nomes de 'Smoked salami' etc. viram '(Snacky Snack) Smoked Salami' e a descrição passa a trazer o efeito). ^c",
        "Traz um arquivo de termos de uso do autor (proíbe uso em coleções). ^c"],
    loads="O manifest declara `<kcd_version>*</kcd_version>`. A regra medida só reconhece versões explícitas e o curinga `1.9.*`; o `*` sozinho não foi medido. O autor atualizou em jun/2026, então é feito para o 1.9.8. ^d",
    systems=["Alimentação (apodrecimento, nutrição, saúde, refresco).", "Buffs temporários de comida (atributos, habilidades, vigor, saúde ao longo do tempo).", "Poções e venenos (alguns).", "Peso e nomes de itens de comida (interface)."],
    newcontent=["9 classes de buff e 42 buffs (por exemplo `buff_energy_snack` com habilidade +3 por 240 s; `buff_combat_snack` com arma +3 por 135 s; `buff_snacky_snack` com capacidade ou atributo +1; `doomsday_poison`).", "5 linhas novas de `consumable_item`; 38 existentes ligadas a buffs."],
    stats=["`food`: nutrição, refresco e saúde de 165 a 174 itens; decaimento de 71 (carnes cozidas 48 → 81 h; defumadas 120 → 220 h; algumas 24 → 0 e 120 → 0).", "`pickable_item`: peso de 44 itens (41 em 0,3; 2 em 0,45; 1 em 0,1) numa coluna `Weight` com W maiúsculo."],
    text=["94 textos trocados e 44 novos em `English_xml.pak` (nomes de item com prefixo '(Snacky Snack)', descrições com o efeito)."],
    assets=["Nenhum (sem textura, modelo ou ícone)."],
    params=["`food.decay_time_hours`, `.nutrition_benefit`, `.refresh_benefit`, `.health_benefit`, `.max_status`; `buff.params` dos 42 buffs novos; `consumable_item.buff_id`."],
    balance=["B1", "B2", "B3", "B4"],
    snippets=[
        ("Um buff de lanche e o item que o dá", "Salami_01 [319a7fe7]            → buff_snacky_snack   cap+25, 360 s\nDried Salami_01 [dc4dde5d]    → buff_snacky_snack   cap+65, mst-33, 360 s\nSmoked Salami_01 [19644921]   → buff_snacky_snack   cap-33, mhe+33, 360 s\nApple [2264f217]              → buff_fruit_snack    mst+125, 55 s\nCarrot cooked [bc26419a]      → buff_combat_snack   weapon_large+3, 135 s",
         "`cap` é capacidade de carga, `mst` vigor máximo, `mhe` vida máxima, `weapon_large` a habilidade com armas de haste. O mod dá efeitos temporários e variados a alimentos comuns: a maçã crua dá +125 de vigor máximo por 55 s; a cenoura cozida dá +3 na habilidade com armas de haste por 135 s. ^c"),
        ("Dois erros de digitação no patch", "food row:  decay_ime_hours=\"...\"   (devia ser decay_time_hours)\npickable_item header:  <column name=\"Weight\" ...>  (o jogo usa weight)",
         "O atributo `decay_ime_hours` não existe no cabeçalho: o motor o ignora e a coluna real `decay_time_hours` fica como a linha a deixa (cópia do jogo ou vazia). Já `Weight` com W maiúsculo não é a coluna `weight` do jogo; se o motor diferenciar maiúsculas, as 44 linhas de `pickable_item` ficam sem peso (regra 5). ^c (fato) / ^n (efeito)")],
    deps=["Nenhuma de arquivo. O autor agradece ao 'kcd pak manager' (ferramenta), que não é necessária para rodar."],
    file_overlap=["Mesma tabela `food` que 1483, 1639, 2345 e, em 6 linhas, 2179; `buff` e `pickable_item` também com 2179 (1 a 6 linhas)."],
    func_overlap=["Concorre com o 2345 em nutrição/refresco/saúde (143 linhas em comum) e com 1483/1639/2345 em apodrecimento."],
    conflicts=["Com 2345: 237 células em comum, 231 diferentes. Com 1483/1639: 68 células de apodrecimento diferentes. Com 2179: 12 células diferentes."],
    errors=["`decay_ime_hours` (erro de digitação em uma linha de `food`) ^c.", "Cabeçalho `Weight` em vez de `weight` em `pickable_item` ^c; efeito sobre o peso é incerto ^n.", "Apodrecimento 0 em 5 carnes cruas, linguiça defumada e banha: pelo jogo, 0 é 'não estraga' ^d.", "Itens de teste e de missão alterados sem relação com comida ^c.", "A linha 'camp pot snack' liga um buff que não é um dos 42 novos (provavelmente um buff do jogo): não verificado ^n."],
    unique=["Sistema de buffs de lanche (único).", "Textos de interface que explicam o efeito do alimento.", "Dá peso e nome mais claros a itens (Carrot, Doomsday)."],
    keep=["A ideia do sistema de lanches (buffs curtos e temáticos), a estrutura das 9 classes de buff e os textos de interface, depois de decidir os números.", "Os valores de apodrecimento seletivos podem ser comparados com os do 2345 linha a linha."],
    reject=["As linhas de itens de teste, de missão e poções (fora do escopo de 'comida do dia a dia'): não copiar para um arquivo consolidado.", "Os zeros em carne crua, até o Q4 ser respondido.", "O cabeçalho `Weight` e o atributo `decay_ime_hours`."],
    questions=["Q4 (apodrecimento 0), Q5 (`Weight`), Q18 (interface dos buffs de lanche)."],
    rank_note="2º de 4 em Comida, bebida e apodrecimento",
    action="Estudar linha a linha na revisão final: é a única fonte de ideias novas do grupo (buffs de lanche) e a que mais espalha mudanças fora do tema. Não copiar o arquivo inteiro.",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["2345"] = dict(
    name="Jesoo333's Food and Drinks Rebalance", author="Jesoo333", version="1.9.7 (30/08/2026)", subcat="food",
    status="Lido por inteiro; nada executado",
    purpose="'Rebalancear os benefícios de nutrição, saúde e refresco de toda comida e bebida do jogo.' (Página do mod.)",
    observed=[
        "Um único arquivo, `Libs/Tables/item/food.xml` **sem sufixo**: substitui a tabela `food` inteira do jogo (202 linhas completas; 155 mudam, 47 são iguais ao jogo, nenhuma é apagada). ^c",
        "Muda `nutrition_benefit` em 139 linhas (mediana: 58 % do valor do jogo), `refresh_benefit` em 98 (mediana 50 %), `health_benefit` em 5 e `decay_time_hours` em 24 (cozidos 48 → 60 h). ^c",
        "Traz um `food.tbl` de 0 byte, como o 1639. ^c",
        "Sem leia-me e sem texto. O nome do mod tem apóstrofo e espaços (`Jesoo333's Food and Drinks Rebalance`): o id derivado é `jesoo333's_food_and_drinks_rebalance`. ^c"],
    loads="O manifest não lista versões. Como a tabela é inteira (sem sufixo), a regra do sufixo/id não se aplica: o arquivo substitui a tabela do jogo, que o motor lê sem checar o nome do mod. ^d",
    systems=["Alimentação: nutrição, refresco, saúde, apodrecimento."],
    newcontent=["Nenhum."],
    stats=["`nutrition_benefit` mediana x0,58 em 139 itens (ex.: 5 → 2,5 em 13 linhas; carne cozida 21–24 → 5); `refresh_benefit` mediana x0,5 em 98 itens (ex.: -6 → -3; Witch potion 8 → -10; Poison -10 → -20); `health_benefit` -10 em 2 itens."],
    text=["Nenhuma mudança de texto."], assets=["Nenhum."],
    params=["`food.nutrition_benefit`, `.refresh_benefit`, `.health_benefit`, `.decay_time_hours`."],
    balance=["B1", "B2"],
    snippets=[("Três linhas de `food`: jogo, 2011 e 2345", "Meat piece cooked [b8f8953c]  nutrition_benefit\n  jogo  24\n  2011  (muda outras colunas)\n+ 2345   5\nBoar meat cooked [db357169]    22 → 5\nBeef_cooked [44593169]         21 → 5",
              "O jogo dá 21 a 24 de nutrição a carne cozida (muito mais do que ao pão ou queijo); o 2345 reduz para 5, no nível de outros alimentos. Efeito: carne deixa de ser a melhor forma de matar a fome, o que aproxima os alimentos entre si. ^d")],
    deps=["Nenhuma."],
    file_overlap=["Substitui `Libs/Tables/item/food.xml` do jogo; a mesma tabela é patcheada por 1483, 1639, 2011 e 2179."],
    func_overlap=["Concorre com o 2011 em nutrição/refresco/saúde e com os três de apodrecimento (24 linhas)."],
    conflicts=["Tabela inteira: pelas regras do jogo, sobrepõe-se a qualquer patch de `food` de outro mod e desfaz as mudanças do 1.9.7/1.9.8 nessa tabela (nenhuma linha do jogo foi apagada nesta cópia). Com o 2011: 231 de 237 células diferentes."],
    errors=["Sem sufixo (decisão de empacotamento que cria o risco acima) ^c.", "`food.tbl` vazio ^n.", "Nome do mod com apóstrofo: não afeta a tabela inteira, mas é um id que o motor reprovaria se houvesse patches ^d."],
    unique=["Rebalanceamento simples e consistente de nutrição e refresco, sem sistema novo.", "Poções de risco mais claramente negativas (Poison -20, Witch -10)."],
    keep=["Os valores de nutrição de carne cozida e de poções, se a direção 'tudo mais próximo' agradar. Podem ser portados como linhas de um patch com sufixo."],
    reject=["O formato (tabela inteira sem sufixo) e o `.tbl` vazio."],
    questions=["Q2 (`.tbl` vazio). Decisão de design: nutrição baixa das carnes cozidas casa com a ideia do autor para o jogo?"],
    rank_note="3º de 4 em Comida, bebida e apodrecimento",
    action="Estudar os números de nutrição e refresco ao lado do 2011; reempacotar qualquer linha aproveitada como patch com sufixo. Não usar o arquivo como está.",
    verdict="warn", verdict_text="Investigar / decidir",
)
