"""Grade B review: curated entries of the weapons group (2045, 2035) and the equipment group (2173, 1380, 2209, 2343)."""

MODS = {}

MODS["2045"] = dict(
    name="Polearms Unleashed Rebalanced Lite Edition (PURLE)", author="AlekseyRaukov", version="1.0 (arquivo 1.1, 2026)", subcat="weapons",
    status="Lido por inteiro; nada executado",
    purpose="'Versão enxuta e reequilibrada do Polearms Unleashed, focada em realismo e jogabilidade básica. A habilidade com armas de haste fica visível e funcional e cada arma de haste tem estatísticas refeitas.' (Página do mod.)",
    observed=[
        "5 paks em `PURLE/Data`: `PolearmUtility` (tabelas de itens e loja, e 2 scripts), `PolearmFeint` (3 tabelas de combate), `PolearmPerfectBlock` (2), `PolearmSkill` (1) e `PolearmAnimations` (animações). ^c",
        "Reequilibra 12 armas de haste em `weapon`, 11 em `melee_weapon`, 10 em `pickable_item` e 8 em `equippable_item`; cria a classe de arma `item_halberd`; acrescenta 30 linhas de estoque em `shop_type2item`. ^c",
        "Combate: 6 ataques novos, 4 movimentos de guarda e 16 modificadores de pose (para fintas de armas de haste), 5 linhas de bloqueio perfeito e 2 de golpe sincronizado. ^c",
        "Torna a habilidade `weapon_large` (23, armas de haste) visível (`hidden` True → False). ^c",
        "Substitui **inteiros** dois arquivos de animação do jogo: `kcd_male_database.adb` (6,3 MB) e `kcd_male_controllerdefs.xml` (98 KB), e acrescenta 4 `blendSpace` de alabarda. ^c",
        "**Dois scripts de depuração:** `polearm.lua` define o comando `unequipitem` ('[Debug] test follower') e `polearm_startup.lua` executa `bind '3' unequipitem`: a tecla 3 passa a desequipar a arma da mão. Nada disso tem relação com armas de haste. ^c"],
    loads="Manifest lista 1.9.4 a 1.9.8; sufixo `PURLE` = nome do mod (`purle`). A versão declarada não foi usada como prova. ^c",
    systems=["Estatísticas de armas de haste (dano por tipo, defesa, força exigida, durabilidade, preço, peso).", "Habilidade `weapon_large` e animações de armas de haste.", "Estoque de lojas.", "Atalho de teclado (efeito colateral)."],
    newcontent=["Classe de arma `item_halberd` e 30 entradas de loja.", "4 blendSpaces de alabarda (animação) e entradas de combate para fintas/bloqueios com armas de haste.", "Comando de console `unequipitem` (depuração)."],
    stats=["Ver B13: `melee_weapon.attack` mediana x0,83; `weapon.defense` x0,93; `weapon.str_req` x1,04; `weapon.max_status` x1,06; `pickable_item.price` mediana x2,96."],
    text=["Nenhum texto alterado."],
    assets=["`kcd_male_database.adb` (6,3 MB) e `kcd_male_controllerdefs.xml`: substituídos; 4 blendSpaces novos."],
    params=["`melee_weapon.attack`, `.slash_att_mod`, `.stab_att_mod`, `.smash_att_mod`; `weapon.defense`, `.str_req`, `.max_status`; `pickable_item.price`, `.weight`; `equippable_item.charisma`."],
    balance=["B13", "B7", "B20"],
    snippets=[("O atalho de depuração escondido", "-- polearm.lua\nfunction unequipPlayer() ... entity.actor:UnequipInventoryItem(weapon) ... end\nSystem.AddCCommand('unequipitem', \"unequipPlayer()\", \"[Debug] test follower\")\n\n-- Startup/polearm_startup.lua\nScript.ReloadScript(\"Scripts/polearm.lua\")\n+ System.ExecuteCommand(\"bind '3' unequipitem\")",
               "O mod liga a tecla `3` a um comando que tira a arma da mão do jogador. Não é parte de armas de haste: é um teste esquecido. Se a tecla 3 já tem um uso do autor, será sobrescrito ao iniciar o jogo. Para uma versão consolidada, esse trecho deve ser **rejeitado**. ^c")],
    deps=["Usa o banco de animações do jogo (`kcd_male_database.adb`), que outros mods também substituem (1563, 2276, 2294, 2049 e o corte de 2372). Só um pode vencer; a fusão por fragmento é viável (já foi feita para o 2049)."],
    file_overlap=["Substitui os mesmos arquivos de animação que outros 4 a 5 mods do conjunto; `pickable_item` com 1062/1380/2173/2179/2209/2011; `skill` (habilidade 23) com 1009 e 85."],
    func_overlap=["Complementar às perks de armas de haste do Perkaholic; sobrepõe-se ao 1558 nos preços e à família 1563/2294 nos ataques."],
    conflicts=["Banco de animações inteiro: só um dos 5 mods.", "Tecla `3`: pode conflitar com atalhos do autor."],
    errors=["Atalho de depuração `bind '3'` ^c.", "O preço de 5 armas sobe mais de 5x (guisarme 1500 → 6000, bill 810 → 6000, alabarda 10 314 → 14 090): números provavelmente escolhidos à mão ^d."],
    unique=["Única reformulação de armas de haste.", "Fintas e bloqueios perfeitos com armas de haste.", "Habilidade de armas de haste visível."],
    keep=["As estatísticas das 12 armas de haste (após revisar os preços).", "As 4 `blendSpace` e as linhas de combate de fintas, se o banco de animações for fundido por fragmento."],
    reject=["`polearm.lua` e `polearm_startup.lua` (depuração).", "A substituição do `kcd_male_database.adb` inteiro."],
    questions=["Q9 (tecla 3)."],
    rank_note="1º de 2 em Armas e munição",
    action="Estudar as estatísticas e as linhas de combate; rejeitar os dois scripts de depuração; fundir animações por fragmento (já testado com o 2049).",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["2035"] = dict(
    name="Ordinance - an Archery Overhaul (DDDB)", author="Diaz Dizazter", version="5.4 (6)", subcat="weapons",
    status="Lido por inteiro; nada executado",
    purpose="'Revisão completa++ de todo o sistema de arco, para Henry e para os NPCs.' (Página do mod.)",
    observed=[
        "8 patches com sufixo `zzdddbordinance` (igual ao `<modid>`): `ammo` (2 novas, 12 alteradas), `equippable_item`/`item`/`pickable_item`/`player_item` (2 flechas novas e 16 preços/pesos), `missile_weapon` (6 alteradas, 17 iguais), `weapon` (13 alteradas, 10 iguais), `weapon_class` (1 alterada: o arco). ^c",
        "Muda o dano das flechas de **perfurante** (`stab_att`) para **cortante e contundente** (`slash_att`, `smash_att`), muda `power_mod`, `str_req`/`agi_req` dos arcos e o preço e peso das flechas. ^c",
        "**Alcance do arco:** `weapon_class` do arco passa de `attack_distance` 30 para 99,1 e de `max_attack_distance` 45 para 150 (3,3x). ^c",
        "2 flechas novas: `arrow_noble_wu` e `arrow_lancelate`. ^c",
        "O pak `scripts.pak` traz `entities/Items/XML/Ammo/Arrow__zzdddbordinance.xml`, uma definição de entidade de flecha com física muito diferente da do jogo (massa 0,3 → 25,3; velocidade 60 → 2666; empuxo e sustentação 0 → 2666; tempo de vida 15 → 90 s; perfuração 9 → 15). O caminho não tem a pasta `Scripts/` que o jogo usa (`Scripts/entities/Items/XML/Ammo/Arrow.xml`) nem corresponde por sufixo: provavelmente não é carregado. ^c (fato) / ^d (inerte)",
        "Dois leia-mes: instruções de instalação (carregar depois de 'doomsday' e 'arsenal'; 'tirar todas as flechas do inventário e pegá-las de novo') e termos de uso do autor. ^c"],
    loads="Manifest `*` (sem lista de versões). O curinga sozinho não foi medido. O autor atualizou em 2026. ^d",
    systems=["Dano e tipo de dano de flechas.", "Estatísticas dos arcos (força e agilidade exigidas, durabilidade, potência).", "Alcance do arco.", "Preços e peso de flechas."],
    newcontent=["2 flechas novas (`arrow_noble_wu`, `arrow_lancelate`) com item, equipável, item do jogador e loja."],
    stats=["Ver B12."],
    text=["Nenhuma."], assets=["Nenhum visual."],
    params=["`ammo.slash_att/stab_att/smash_att/power_mod`; `missile_weapon.power`; `weapon.agi_req/str_req/max_status`; `weapon_class.attack_distance/max_attack_distance`; `pickable_item.price/weight`."],
    balance=["B12"],
    snippets=[("Alcance do arco", "weapon_class (arco)\n  attack_distance      30  → 99,1\n  max_attack_distance  45  → 150\n  collision_mode        1  → 2",
               "Quanto o jogo considera 'em alcance' para um alvo de arco (usado pela IA e pelo cálculo de acerto). Triplicar a distância faz os NPCs arqueiros atirarem de muito mais longe, e o jogador também. É o maior valor do mod. ^d"),
              ("Tipo de dano das flechas", "arrow_cheap_02    stab 15 → 0   slash 0 → 6,66\narrow_gray        stab 12 → 0   slash 0 → 9,2\narrow_light       stab  0 → 0   slash 0 → 9",
               "O jogo dá às flechas dano perfurante (stab); o mod troca para cortante (slash) e contundente (smash). Armadura e gibão resistem de modo diferente a cada tipo: flecha cortante é pior contra armadura de placas, melhor contra pano. ^d")],
    deps=["O leia-me manda carregar depois de 'doomsday' e 'arsenal' (outros mods do autor, não presentes aqui)."],
    file_overlap=["`ammo` com 2179 (24 células); `pickable_item` com 2011, 2173, 1062, 1380, 2045, 2209; `weapon`/`equippable_item` com 2045."],
    func_overlap=["Concorre com o 2179 nas flechas e, pelas linhas de `ammo` e `missile_weapon`, com mods de arco de outros graus (ver a sobreposição calculada)."],
    conflicts=["Com 2179: as mesmas flechas, 24 de 24 células diferentes."],
    errors=["Atributos de outra tabela (`charisma`, `conspicuousness`, `rpg_buff_weight`, `social_class_id`, `visibility`, `wealth_level`) copiados em linhas de `pickable_item`: ignorados pelo motor ^d.", "Entidade de flecha sem raiz `Scripts/` ^d.", "Alcance 3,3x sem justificativa no leia-me ^c."],
    unique=["Tipos de dano diferentes por flecha; alcance do arco; 2 flechas novas."],
    keep=["A ideia de dano cortante e contundente por tipo de flecha (como uma opção a avaliar) e as 2 flechas novas, se o design pedir mais variedade."],
    reject=["O alcance 99,1/150 e a física da entidade de flecha (valores extremos, sem teste)."],
    questions=["Q12 (físicas); como o alcance do arco se comporta com a IA?"],
    rank_note="2º de 2 em Armas e munição",
    action="Estudar o dano por tipo de flecha junto com o 2179 e os mods de arco (B12). Não usar o alcance nem a entidade.",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["2173"] = dict(
    name="True Hardcore Maintenance (PTF)", author="Nfrog2swamp1", version="1.0 (arquivo 2.0)", subcat="equipment", family="True Hardcore",
    status="Lido por inteiro; nada executado",
    purpose="'Rebalanceia kits de reparo, faz pagar o custo completo do reparo nas lojas e remove kits de reparo dos inventários de inimigos e acampamentos.' (Página do mod.)",
    observed=[
        "8 patches com sufixo `truehardcoremaintenance` (igual ao `<modid>`): `armor` (20), `ointment_item` (1), `pickable_item` (8), `buff` (2), `perk_rpg_param_override` (4), `rpg_param` (5 novas, 2 alteradas), `skill2item_category` (2 novas) e `inventory_preset2item` (4). Cada `.xml` vem com um `.tbl`. ^c",
        "`armor`: 20 selas de cavalo (`horse_saddle_001` a `004` e variantes) passam de `max_status` 0 para 30 a 60: as selas agora se desgastam. As mesmas 20 linhas apagam as colunas de editor `computer_name` e `timestamp` (40 células iguais ao valor de referência de 2020). ^c",
        "`pickable_item`: preço dos kits de reparo x1,5 e peso x2 a x5. `ointment_item`: kit de armadura pequeno com eficiência 0,5 → 0,2. ^c",
        "`inventory_preset2item`: `amount_random_add` 1 → 0 para os kits pequenos de armadura e de arma (4 linhas): NPCs deixam de carregar kits extras. ^c",
        "`rpg_param`: `RepairKitCapacity` 200 → 600, `RepairPriceModif` 0,65 → 1 (preço cheio), 5 chaves novas de reparo. `skill2item_category`: selas e bridas passam a ser reparáveis. ^c"],
    loads="Manifest sem lista de versões; sufixo igual ao id. ^c",
    systems=["Reparo (kits, preços, capacidade).", "Durabilidade das selas.", "Inventário dos NPCs (kits).", "Perks de manutenção (Well maintained, Weapon cruncher)."],
    newcontent=["Nenhum item novo; 2 categorias de reparo novas (sela e brida)."],
    stats=["Ver B14."],
    text=["2 textos alterados (perks Well maintained e Weapon cruncher, 15 % → 10 % e 15 % → 5 %)."], assets=["Nenhum."],
    params=["`RepairKitCapacity` 200→600 (Hardcore 450→600); `RepairPriceModif` 0,65→1 (Hardcore 0,9→1); `RepairKitItemHealthBestLimit` 0,1; `RepairKitItemHealthDefaultLimit` 0,9; `RepairKitMaxSkillCapacityCoef` 2."],
    balance=["B14"],
    snippets=[("Preço e peso dos kits", "armourKit        price 2000 → 3000   weight 1 → 2\nweaponKit        price 2000 → 3000   weight 1 → 2\narmourKit_small  price  600 →  900   weight 0,5 → 1\ncobblersKit_small price 300 →  450   weight 0,1 → 0,5",
               "Os kits de reparo ficam 50 % mais caros e 2 a 5 vezes mais pesados, mas cada um repara mais (capacidade 200 → 600). O efeito líquido é pagar mais por uso, carregar mais peso, e ter menos kits soltos nos inimigos. ^c")],
    deps=["Nenhuma. Faz parte de uma família 'True Hardcore' (2173, 2179, 2188, 2208, 2209, 2210, 2219); os outros não são necessários."],
    file_overlap=["`rpg_param`/`perk_rpg_param_override` com 1558, 1112, 1384, 2179; `armor` com 1380 e 2209; `pickable_item` com 2011, 2035, 2045, 1062."],
    func_overlap=["Concorre com o 1558 no reparo (`RepairKitCapacity` 8000)."],
    conflicts=["Com 1558: 4 de 6 células diferentes."],
    errors=["Chave `DamageToArmorStatusHigherLayers` não consta de nenhuma lista lida ^n.", "Apaga `computer_name`/`timestamp`: sem efeito de jogo, é ruído ^c.", "`max_status` das selas sem uma perk ou preço que as acompanhe: pode superar ou dobrar o 1545 'Saddles Have Durability' ^d."],
    unique=["Remove kits de reparo dos inventários de NPCs.", "Selas e bridas reparáveis."],
    keep=["Todo o conjunto de reparo, como um bloco único e coerente (nota: contradiz o 1558)."],
    reject=["As linhas de metadados de editor."],
    questions=["Q12, Q14."],
    rank_note="1º de 4 em Equipamento: conteúdo, manutenção e visual",
    action="Candidato do grupo de equipamento; resolver o conflito de valores de reparo com o 1558 e com o `krs_qol`.",
    verdict="ok", verdict_text="Candidato",
)

MODS["1380"] = dict(
    name="Black Items - PTF", author="DarkDevil428", version="1.0 (arquivo 1.1, 2026)", subcat="equipment",
    status="Lido por inteiro; nada executado",
    purpose="'Corrige itens que deveriam ser pretos mas são vinho, cinza etc., renomeando-os para as cores certas, e acrescenta versões pretas independentes.' (Página do mod.)",
    observed=[
        "8 patches com sufixo `black_items` (= id derivado de 'Black Items'): `armor`, `clothing`, `clothing_raycast`, `equippable_item`, `item`, `pickable_item`, `player_item` (6 novos + 5 alterados) e `shop_type2item` (17). ^c",
        "6 peças novas pretas (chaperon, calções 'fashionable', calções justos, calções amarelo-preto, gibão 'pourpoint', ombreiras de brigantina) com estatísticas (charisma 9 a 16). ^c",
        "Renomeia 5 itens do jogo cujo nome não bate com a cor (ex.: 'Black chaperone' vira 'Burgundy chaperon'); 9 textos alterados e 11 novos em CZ, EN e DE. ^c",
        "Traz um material e duas texturas (`black_pourpoint_diff.dds` 5,6 MB e `_spec.dds` 2,8 MB). ^c"],
    loads="Manifest lista 1.9.4 a 1.9.9; sufixo = id. ^c",
    systems=["Roupa e armadura (itens novos).", "Estoque de lojas.", "Nomes de itens."],
    newcontent=["6 itens novos (cada um em `item`, `clothing`, `armor`, `equippable_item`, `pickable_item`, `player_item`).", "17 entradas de loja."],
    stats=["Charisma dos 6 itens novos: 16, 13, 12, 9, 12 e 9 (valores próprios)."],
    text=["9 textos alterados e 11 novos em 3 idiomas."], assets=["`black_pourpoint.mtl`, `_diff.dds` (5,6 MB), `_spec.dds` (2,8 MB)."],
    params=["`equippable_item.charisma`, `pickable_item.price`, `shop_type2item.amount`."],
    balance=["B20"],
    snippets=[("Renomear em vez de trocar", "ui_nm_chaperon_001_black   jogo 'Black chaperone'\n+                          mod  'Burgundy chaperon'\n+ ui_nm_black_chaperon (novo) 'Black chaperon'",
               "O item do jogo continua o mesmo, mas passa a ter o nome da cor real (vinho). A peça preta verdadeira é um item novo. Não muda estatística nenhuma do jogo. ^c")],
    deps=["Nenhuma."],
    file_overlap=["Tabelas de item com 2209, 2035, 2011 e 2173, sem linhas em comum."],
    func_overlap=["Nenhuma."],
    conflicts=["Nenhum encontrado."],
    errors=["`armor` traz `computer_name` de editor (JBARTONEK-DT etc.): ruído ^c."],
    unique=["Correção de nomes de cor; 6 peças pretas."],
    keep=["As correções de nome (9 textos): úteis, de risco baixo."],
    reject=["Nada."],
    questions=["Interessam peças novas de roupa (conteúdo) ou só as correções de nome?"],
    rank_note="2º de 4 em Equipamento: conteúdo, manutenção e visual",
    action="Conteúdo limpo; só as correções de nome entram no escopo de balanceamento. Decidir se as peças novas pertencem ao projeto.",
    verdict="info", verdict_text="Conteúdo novo",
)

MODS["2209"] = dict(
    name="Poisonous Enemies - True Hardcore Compatibility Patch (PTF)", author="Nfrog2swamp1", version="1.0", subcat="equipment", family="True Hardcore",
    status="Lido por inteiro; nada executado",
    purpose="'Oferece dois patches de compatibilidade para o Poisonous Enemies, para usar com a série True Hardcore.' (Página do mod.)",
    observed=[
        "Três paks: `Scripts.pak` com `Scripts/Utils/PoisonousUtils.lua` (464 linhas), o pak de tabelas e um pak de texto. ^c",
        "O script define `poisonousUtils:OnHit()` e `GetPoisoned()`: quando o jogador toma dano, sorteia (por facção do inimigo) se ele é envenenado, e aplica um de 11 venenos (acônito, arsênico, beladona etc.) por `player.soul:AddBuff`. ^c",
        "Tabelas: 2 itens novos (capuz e luvas de envenenador, com tipos de armadura 67 e 68 e buffs), 26 linhas de `shop_type2item` com `amount` 0 (estoque inicial 0). ^c",
        "3 textos novos: 'opium', 'dollmaker', 'lullaby'. ^c"],
    loads="Manifest sem versões; sufixo `patchtruehardcorepoisonousenemies` = id. ^c",
    systems=["Inimigos que envenenam o jogador (por script).", "Armadura de proteção (capuz e luvas de envenenador).", "Lojas."],
    newcontent=["2 itens de armadura, 2 buffs e 11 venenos disparados por script."],
    stats=["Probabilidades de veneno por facção no script (1/6, 1/5, 1/4, 1/3, 1/2 conforme o grupo)."],
    text=["3 textos novos."], assets=["Nenhum."],
    params=["Chances `math.random(1,N)` por grupo de facção no Lua."],
    balance=["B20"],
    snippets=[("Sorteio por facção", "local poisonChanceVeryLow = math.random(1, 6)\n...\nif poisonChanceVeryLow == 1 and (entityFaction == 27 or entityFaction == 40 or ...) then ... end",
               "A cada golpe sofrido, o script rola um dado por tipo de facção: 1 em 6 para civis e vagabundos, 1 em 5 para bandidos, 1 em 4 para cumanos e soldados de eventos, 1 em 3 para soldados e bandos maiores, 1 em 2 para falsários, rangers e mineiros hostis. Com o dado certo, escolhe um veneno e aplica o buff ao jogador. ^c")],
    deps=["**Depende do mod 1807 (Poisonous Enemies)**: é um remendo; o `PoisonousUtils.lua` substitui o do mod original (mesmo caminho). Sem o 1807 não há quem chame o script (Q11)."],
    file_overlap=["`armor`/`buff`/`pickable_item`/`player_item`/`shop_type2item` com 1380 e 2173, sem linhas em comum."],
    func_overlap=["Da mesma família True Hardcore (2173, 2179); ver família."],
    conflicts=["Com o 1807: substitui o script original (esperado)."],
    errors=["As 26 linhas de loja com quantidade 0 são provavelmente reservas para o 1807 ^d.", "`GetPoisoned` escolhe quem envenenou pela direção da câmera do jogador (raio de 50 m) e não pelo atacante: pode culpar a facção errada ^c."],
    unique=["Único mod do conjunto que envenena o jogador por script."],
    keep=["Só faz sentido com o 1807. Registrar como dependência."],
    reject=["Nada, mas não usar sozinho."],
    questions=["Q11."],
    rank_note="3º de 4 em Equipamento: conteúdo, manutenção e visual",
    action="Deixar para o dia em que o 1807 entrar na lista; sem ele, é inerte.",
    verdict="info", verdict_text="Depende de outro mod",
)

MODS["2343"] = dict(
    name="Ultimate Horse Caparison Fix", author="CromwellForge", version="1.0 (24/08/2026)", subcat="equipment",
    status="Lido por inteiro; nada executado",
    purpose="'Corrige a crina do cavalo atravessando as caparaçonas, preservando a cauda. Caparaçonas de cobertura total escondem a crina; as de pescoço aberto a mantêm.' (Página do mod.)",
    observed=[
        "Um pak com um script de **1215 linhas** (`Scripts/Mods/ultimate_horse_caparison_fix.lua`, rótulo `TEST53B AL-BURAQ RUNTIME`): troca o cabelo do cavalo em tempo de execução (`soul:OverrideHair`), religa-se depois de dormir (`OnBedStop`) e ouve eventos da interface do inventário do cavalo. ^c",
        "Substitui `Libs/UI/UIActions/IGM_Inventory.xml` do jogo (grafo de ações da interface do inventário): acrescenta 61 linhas (nós `KCDMS_TEST49_OnUseItem` e `OnTryItem`, ligados a tokens de jogo), sem apagar nenhuma. ^c",
        "Cria o token de jogo `kcd_sedivka` (`TryItemWuid`, `UseItemWuid`). ^c",
        "2 linhas novas em `character_hair` (crina completa e só cauda) e 4 almas de cavalo (`horse_sedivka`, `rat_hanuses_horse`, `rat_kobylas_horse`, `tal_boreks_horse`) com o cabelo trocado. ^c",
        "Dois modelos de pelo (`.skin`, 0,9 MB e 0,4 MB) e uma cópia idêntica ao jogo de `sh1_p2_l1_v0.skin`. README e CHANGELOG. ^c"],
    loads="Manifest `1.9.*`; sufixo `ultimate_horse_caparison_fix` = id. ^c",
    systems=["Aparência do cavalo (crina, cauda).", "Interface do inventário do cavalo.", "Eventos do jogador (despertar)."],
    newcontent=["2 cabelos de cavalo; 1 token de jogo."],
    stats=["Nenhuma estatística de jogo."],
    text=["Nenhum texto."], assets=["2 `.skin` de cabelo; 1 `.skin` copiado do jogo."],
    params=["Tempos do script: `intervalMilliseconds = 2500`, `maximumPasses = 8`."],
    balance=[],
    snippets=[("Nós acrescentados ao grafo do inventário", "<!-- KCD TEST41: parallel diagnostic/functional intent bridge -->\n+ <Node Id=\"9201\" Class=\"System:ExecuteScript\">\n+   <Inputs Script=\"KCDMS_TEST49_OnUseItem()\" />\n+ <Node Id=\"9701\" Class=\"Mission:GameTokenSet\"> gametoken_Token=\"kcd_sedivka.TryItemWuid\"",
               "Quando o jogador usa ou tenta um item do inventário do cavalo, o grafo chama funções Lua do mod e grava o item em tokens. Os rótulos 'TEST41', 'TEST49', 'TEST53B' mostram que é código de teste que virou lançamento. Como a modificação é só aditiva, deve coexistir com outros mods que também mexem no grafo, desde que não substituam o mesmo arquivo. ^c")],
    deps=["Nenhuma de arquivo; depende do script e do arquivo de UI trabalharem juntos."],
    file_overlap=["Substitui `IGM_Inventory.xml` do jogo; `Inventory.gfx` (2318) é outro arquivo da mesma interface."],
    func_overlap=["Nenhuma de balanceamento."],
    conflicts=["Possível com qualquer mod que substitua `IGM_Inventory.xml` ou toque `OnBedStop` do jogador (Q10)."],
    errors=["Rótulos e logs de teste no código final ^c.", "Substituição de arquivo de interface do jogo (risco em atualizações) ^c.", "`kcd_sedivka` como token de jogo permanente ^c."],
    unique=["Cabelo dinâmico de cavalo."],
    keep=["Possivelmente a ideia (cabelo de cavalo por estado da caparaçona), por ser visual; o código está longe do estado final."],
    reject=["O arquivo de interface substituído e os logs de teste."],
    questions=["Q10."],
    rank_note="4º de 4 em Equipamento: conteúdo, manutenção e visual",
    action="Fora do foco de balanceamento. Só considerar se o projeto abraçar correções visuais de cavalo.",
    verdict="bad", verdict_text="Fora de escopo / arriscado",
)
