"""
Grade B review: the balancing changes, each explained (what it is, what the original value is, what the mod changes it to, what depends on it,
why the author probably did it, what it does in practice, who else touches it, is it reasonable).

`rows` is either a literal list [(label, was, is)] or a spec resolved by tools/build_grade_b_page.py from the machine-derived files:
    {"type": "params", "params": [...], "mods": [...]}                     rpg_param matrix: game default (runtime/table) and each mod's value
    {"type": "cells", "table": t, "column": c, "mods": [...], "keys": [substrings or None], "limit": n, "variant": {"1483": "2X"}}
    {"type": "wide", "mod": id, "cols": [(table, column), ...], "limit": n}   one row per item, several columns old -> new
    {"type": "perkcat", "mod": "1009"}                                      the 56 perks of Perkaholic with level, skill, buff formula and text
"""

BALANCE = [
    dict(id="B1", title="Quanto tempo a comida leva para estragar", mods="1483, 1639, 2011, 2345", dims=["Sobrevivência", "Economia", "Ritmo"],
         scope="Local (tabela `food`); propaga para caça, cozinha e comércio",
         what="O tempo, em horas de jogo, até um alimento perecível estragar (coluna `decay_time_hours` de `food`).",
         rows={"type": "cells", "table": "food", "column": "decay_time_hours", "mods": ["1483", "1639", "2011", "2345"], "variant": {"1483": "2X"},
               "keys": ["Smoked Rabbit meat", "Boar meat cooked", "Beef_cooked", "sheep_kidney cooked", "cream [", "herring", "Bacon", "Dead Chicken", "Smoked Salami_01", "dog_lard", "Beef [", "lamb_meat ["], "limit": 14},
         meaning="24 horas é um dia. O valor 0 é 'não estraga' (91 das 202 linhas: poções, vinho, cerveja, itens de teste). A comida estragada some do inventário ou fica podre e perigosa de comer; por isso este número decide quanto se pode carregar, estocar e vender. ^c (colunas e valores) / ^d (zero = não estraga)",
         why="O leia-me do 1483 compara com o jogo: maçã 5 dias, lebre 1 dia, pão 4 dias. 'Dobrar dá um colchão e ainda é imersivo; 3x parece irreal.' O 2011 e o 2345 escolhem valores por item em vez de um múltiplo. ^c",
         effect="1483 e 1639 (2X): tudo dura o dobro; o jogador deixa de perder comida em uma viagem longa. 1483 5X: carne defumada dura 25 dias, quase irrelevante. 2345: só 24 linhas de cozidos sobem de 48 para 60 h (25 %): ajuste mínimo. 2011: cozidas 48 → 81 (69 %), defumadas 120 → 220 (83 %), mas **carnes cruas e linguiça com 0** (nunca estragam, ^d), o que apaga o motivo de cozinhar. ^d",
         others="Cinco a oito outros mods graduados escrevem nas mesmas linhas (2124, 2299, 651, 1926, 2210...). Entre os 4 deste grupo: valores diferentes em todas as células em comum, exceto 110 de 111 entre 1483 (2X) e 1639.",
         verdict="Dois jeitos: múltiplo uniforme (1483, o mais limpo) e valor por item (2011, 2345). Os zeros do 2011 e a linha 2400 do 1639 são erros prováveis. Sugestão para a revisão final: partir do 2X do 1483 e aceitar exceções por item só com motivo. ^d", conf="d"),

    dict(id="B2", title="Quanto cada alimento nutre, refresca e cura", mods="2011, 2345 (2179 em 6 itens)", dims=["Sobrevivência", "Dificuldade"],
         scope="Local (`food`), mas muda o valor de qualquer refeição",
         what="`nutrition_benefit` (fome), `refresh_benefit` (efeito de 'refresco' do alimento; negativo cansa) e `health_benefit` (vida) dos alimentos e poções.",
         rows={"type": "cells", "table": "food", "column": "nutrition_benefit", "mods": ["2011", "2345"], "keys": ["Meat piece cooked", "Boar meat cooked", "Poison [", "Dollmaker potion", "Witch potion", "Sleeping potion", "Antidote", "Aqua Vitalis", "Stamina potion", "Marigold decoction"], "limit": 12},
         meaning="No jogo, `nutrition_benefit` é quanto a barra de fome sobe; carne cozida dá 21 a 24 (muito mais do que pão ou queijo). O 2345 reduz esses valores e o 2011 reescreve muitos para valores negativos em poções (Sleeping potion 5 → -30). ^c (valores) / ^d (significado de cada coluna)",
         why="2345 (resumo da página): 'rebalancear os benefícios de nutrição, saúde e refresco de toda comida e bebida'. A direção observada é aproximar os alimentos entre si e tornar poções e venenos claramente ruins. O 2011 acrescenta saúde (health 0 → 1 a 8) a quase todo alimento comum. ^d",
         effect="2345: cada refeição enche menos (mediana 58 % do valor do jogo): mais refeições e mais comida a carregar; carne deixa de ser melhor que pão. 2011: comida passa a curar pouco e continuamente; poções 'de brincadeira' passam a ter efeito colateral (valores negativos). ^d",
         others="Os dois mods concorrem em 143 linhas (140 em conflito) e 237 células, com 6 células iguais. Outros 6 a 8 mods graduados (2124, 2299, 651, 1926, 2210) também escrevem em `food`.",
         verdict="Não somam: ou um ou outro (e o 2345, por ser tabela inteira, vence qualquer patch). O ponto interessante para a revisão final é a **direção** (aproximar alimentos), que pode ser reproduzida com poucos valores. ^d", conf="d"),

    dict(id="B3", title="Chefs Kiss: um sistema novo de buffs de lanche", mods="2011", dims=["Sobrevivência", "Progressão", "Conteúdo novo"],
         scope="Propaga para atributos, habilidades, vigor e vida",
         what="38 alimentos comuns ganham um buff temporário ao serem comidos; os buffs são 42 linhas novas de `buff` em 9 classes novas.",
         rows=[("Apple (maçã crua)", "sem efeito", "`mst+125` vigor máximo por 55 s"), ("pear (pera)", "sem efeito", "`mst+90` por 90 s"), ("carrot (cenoura)", "sem efeito", "`srg+27/t` regeneração de vigor por 30 s"),
               ("Onion (cebola)", "sem efeito", "`srg+46/t` por 5 s"), ("Horseradish (raiz-forte)", "sem efeito", "`health+35/t` por 2 s"), ("Horseradish cooked", "sem efeito", "`health+14/t` por 35 s"),
               ("carrot cooked", "sem efeito", "habilidade armas de haste +3 por 135 s"), ("Onion cooked", "sem efeito", "esgrima +3 por 135 s"), ("Garlic cooked", "sem efeito", "machado +3 por 135 s"),
               ("Beet cooked", "sem efeito", "arco +3 por 135 s"), ("cabbage cooked", "sem efeito", "espada +3 por 135 s"), ("Radish cooked", "sem efeito", "maça +3 por 135 s"),
               ("egg", "sem efeito", "furtividade +2 por 240 s"), ("hardboiled_egg", "sem efeito", "andar e correr +2 por 240 s"), ("Dried pear", "sem efeito", "velocidade de corrida +0,11 por 240 s"),
               ("Griddlecake", "sem efeito", "custo de corrida x1,1 (`StaminaSprint*1.1`) por 240 s"), ("Pretzel", "sem efeito", "arrombamento +3 por 240 s"), ("honey", "sem efeito", "alquimia +2 por 240 s"),
               ("Salami_01", "sem efeito", "capacidade +25 por 360 s"), ("Dried Salami_01", "sem efeito", "capacidade +65, vigor máximo -33 por 360 s"), ("Smoked Salami_01", "sem efeito", "capacidade -33, vida máxima +33 por 360 s"),
               ("porridge", "sem efeito", "vitalidade +1 por 180 s"), ("bowl_mash", "sem efeito", "força +1 por 180 s")],
         meaning="`mst` é vigor máximo, `srg` regeneração de vigor, `cap` capacidade de carga, `mhe` vida máxima, `/t` significa 'por tick' (valor aplicado continuamente), e `weapon_*+3` soma 3 níveis à habilidade. As durações são em segundos de jogo. Cada classe (Combat Snack, Fruit Snack, Energy Snack ...) é só o rótulo do tipo de buff na interface. ^c (códigos, lidos no próprio mod) / ^d (leitura de `/t`)",
         why="A página do mod fala em 'novas regras para comida, bebida e buffs'. A ideia: comida comum deixa de ser só fome e vira uma pequena escolha tática (comer ovo antes de se esconder, cebola antes de correr). ^d",
         effect="Efeitos pequenos e curtos (2 a 6 minutos de jogo) em muitos itens. Habilidade +3 em armas por 135 s é um bônus real em combate; `health+35/t` por 2 s é cura imediata de uma raiz. O risco é de **inflação de buffs**: comer vira rotina antes de lutar e o sistema de poções perde valor. ^d",
         others="Nenhum outro mod do conjunto cria buffs de comida. Os buffs do 2179 (35 alterados) são de poções e de perks, não de comida.",
         verdict="Ideia boa e isolada; números não avaliados. Merece estudo à parte e só se o projeto quiser tática de comida. Itens de teste ligados aos buffs devem sair (B4). ^d", conf="d"),

    dict(id="B4", title="Itens de teste e de missão que o Chefs Kiss também mexe", mods="2011", dims=["Escopo", "Risco de erro"],
         scope="Propaga: afeta itens fora do tema",
         what="Linhas de `food` e `consumable_item` de itens que não são comida do dia a dia: poções de teste e de missão, itens de depuração e venenos.",
         rows={"type": "cells", "table": "food", "column": "health_benefit", "mods": ["2011"], "keys": ["crystal meth", "charl_horndust", "OintmentForMarta", "Mrchojedy Cure", "Deadly potion", "Test Potion: Invincible", "Abortion potion", "Dementia potion", "Diarrhoea potion", "Generic potion"], "limit": 12},
         meaning="Estes itens existem na tabela `food` do jogo, mas são de teste ('crystal meth', 'Generic potion', 'Test Potion: Invincible'), de missão ('OintmentForMarta', 'Mrchojedy Cure') ou venenos de enredo. Mudar a saúde/nutrição deles só tem efeito para quem os conseguir com console ou mod. ^c (itens) / ^d (uso no jogo)",
         why="Provavelmente o autor varreu a tabela `food` inteira e reescreveu todas as linhas, inclusive as de teste. Não parece intenção. ^d",
         effect="Para o jogador comum, nenhum efeito (os itens não aparecem). Se algum for obtido (por outro mod ou comando), 'charl_horndust' passa a curar 420 e 'Generic potion' vira `doomsday_poison` (`poi=1, health-175/t`, 1 s): 175 de dano por tick de veneno. ^d",
         others="Nenhum outro mod do grupo toca esses itens.",
         verdict="Não copiar para a versão consolidada. É a prova de que o 2011 espalha mudanças por toda a tabela; qualquer aproveitamento tem de ser por linha escolhida. ^c", conf="c"),

    dict(id="B5", title="Ritmo e agressividade da IA em combate (`CombatAuto*`)", mods="2179, 1384, 1112, 1558", dims=["IA", "Dificuldade", "Ritmo"],
         scope="Propaga para todo combate contra NPCs",
         what="Constantes que dizem à IA quanto esperar entre ataques, quantos passos de combo fazer, quando tentar truques e quando mudar de zona de ataque.",
         rows={"type": "params", "mods": ["2179", "1384", "1112", "1558"], "params": ["CombatAutoMaxAttackDelay", "CombatAutoAttackDelayIncreasePerAttacker", "CombatAutoAttackDelaySigma", "CombatAutoMasterComboSteps", "CombatAutoNaturalComboRatio", "CombatAutoTrickAttackProb", "CombatAutoTrickReactionMaxDelay", "CombatAutoZoneChangeDelayMaxMax", "CombatAutoZoneChangeDelayMinMax", "CombatAutoReactivePreblockMaxDelay", "CombatAutoForcedComboStaminaLimit", "CombatAutoRiposteAggressionWeight"]},
         meaning="`CombatAutoMaxAttackDelay` é o tempo máximo entre ataques da IA; 6 s no jogo. 0,01 significa ataque praticamente contínuo. `...IncreasePerAttacker` diz quanto o atraso cresce por atacante (com vários inimigos, cada um espera mais). As demais controlam combos e zonas. Os comentários do próprio jogo (Params Reference) descrevem a maioria. ^c",
         why="Todos os quatro querem inimigos mais agressivos e menos previsíveis. 1112 e 1384 zeram o atraso; 2179 reduz pela metade; 1558 para 1,5. As constantes novas (`...Sigma`, `...ComboStepsSigma`, `...ZoneChange...`) do 1112/1384/2179 definem variação e tempo de troca de zona. ^d",
         effect="Com 0,01 (1112 e 1384) os inimigos praticamente não param entre golpes: o combate vira uma pressão contínua que só o bloqueio e o vigor contêm. Com 3 (2179) o ritmo é cerca do dobro do jogo; com 1,5 (1558), 4 vezes. Em grupos, `...PerAttacker` mais baixo (0,3 a 0,5 contra 0,55 a 0,8) deixa vários inimigos atacando quase juntos. ^d",
         others="Os quatro deste grupo e outros mods graduados (ver a sobreposição calculada) mexem nos mesmos parâmetros; `CombatAutoMaxAttackDelay` é escrito por 11 mods.",
         verdict="Contradição direta: são 4 valores diferentes para o mesmo parâmetro. Valor extremo (0,01) deve ser testado antes de qualquer decisão; o ponto de partida mais seguro é o 2179 (3). Não somar: o último na ordem vence. ^d", conf="d"),

    dict(id="B6", title="Pesos de bloqueio, esquiva e 'sem defesa' da IA", mods="2179, 1384, 1112, 1558", dims=["IA", "Dificuldade"],
         scope="Propaga para todo combate contra NPCs",
         what="A probabilidade relativa de a IA escolher cada defesa: bloqueio normal, bloqueio perfeito, bloqueio perfeito especial, esquiva ou nenhuma defesa.",
         rows={"type": "params", "mods": ["2179", "1384", "1112", "1558"], "params": ["CombatAutoPBWeight", "CombatAutoSPBWeight", "CombatAutoNormalBWeight", "CombatAutoNoDefenseWeight", "CombatAutoDodgeWeight", "CombatAutoUnarmedBlockProb", "MaxPerfectBlockSlotModifier", "MaxSpecialPerfectBlockSlotModifier"]},
         meaning="'PB' é bloqueio perfeito (aquele que abre o riposte), 'SPB' o perfeito especial (de golpe mestre), 'NormalB' o bloqueio comum, 'NoDefense' a chance de nem tentar se defender. São pesos: quanto maior o valor em relação aos outros, mais a IA escolhe aquela defesa. `MaxPerfectBlockSlotModifier` limita o espaço de tempo do bloqueio perfeito do jogador. ^c (nomes e descrições da referência) / ^d (efeito)",
         why="Cada mod tem outra ideia. 1112: mais defesa, com bloqueio perfeito forte (3,85), bloqueio normal 3,475 e nunca sem defesa (0). 1384: esquiva muito mais provável (4) e perfeito um pouco menor (2). 2179: bloqueio perfeito 1,8 e perfeito especial quase eliminado (0,2). 1558: bloqueio perfeito 0,9 e especial 0,5, mas 'sem defesa' sobe para 0,6 e bloqueio sem arma para 3. ^d",
         effect="1112 e 1384 deixam o inimigo sempre se defendendo (golpes do jogador mais barrados); o 1558 o deixa baixar a guarda mais vezes. Pesos de bloqueio perfeito baixos (2179, 1558) significam menos ripostes da IA contra o jogador; o 1112 faz o oposto. A janela do jogador `MaxPerfectBlockSlotModifier` 0,85 → 0,5 a 0,7 encurta o tempo útil do bloqueio perfeito do jogador (mais difícil) em todos os quatro. ^d",
         others="`CombatAutoSPBWeight` é escrito por 12 mods; `CombatAutoPBWeight` por 10; as quatro versões deste grupo se contradizem em todos os pesos.",
         verdict="Os quatro divergem; o mais conservador no conjunto é o 2179 (pesos baixos de PB/SPB, janela 0,6). Só decidir com teste de combate (Q7). ^d", conf="d"),

    dict(id="B7", title="Linhas de bloqueio perfeito por direção (`combat_action_perfect_block`)", mods="1112, 1384 (2045 em 5 linhas)", dims=["Combate", "IA", "Conteúdo novo"],
         scope="Local (uma tabela), mas decide como os bloqueios perfeitos são sincronizados",
         what="Linhas novas na tabela que casa a animação de um bloqueio perfeito com o golpe do adversário: tipo de ação, zona de ataque, zona de bloqueio, mão e armas.",
         rows=[("Linhas novas no 1112", "-", "156 (154 chaves distintas); 12 iguais ao jogo"), ("Linhas novas no 1384", "-", "150 (148 chaves distintas); 2 iguais ao jogo"), ("Idênticas entre 1112 e 1384", "-", "130 de 150"), ("Só no 1112 / só no 1384", "-", "24 / 18"), ("Linhas novas no 2045 (armas de haste)", "-", "5 + 2 de sync_pb_hit"),
               ("Linhas da tabela no jogo 1.9.8", "358", "358 + novas")],
         meaning="A tabela diz qual animação de bloqueio responde a qual golpe e em que instante o bloqueio vale como 'perfeito' (colunas `perfect_block_window`, `block_time_to_hit`...). As linhas novas acrescentam combinações de zona ('direção') que não existem no jogo. Com elas, o bloqueio perfeito exige encontrar o lado certo. ^c (estrutura) / ^d (efeito)",
         why="1384 'Mestre exige direção, bloqueio perfeito exige lado'; 1112 'faz o combate direcional valer'. ^c",
         effect="Sem as linhas, o jogo sincroniza o bloqueio perfeito com um conjunto menor de combinações; com elas, o bloqueio perfeito deixa de acontecer em golpes que o jogo considerava cobertos por qualquer lado. O efeito líquido é um combate mais técnico. Em jogo a jogabilidade não foi testada. ^d",
         others="Só 1112, 1384 e 2045. 1112 e 1384 são, na prática, a mesma tabela (130 linhas idênticas das 150 do 1384).",
         verdict="Usar apenas uma das duas fontes; o 1112 tem 24 linhas a mais e o 1384, 18 só dele. Comparar essas 42 linhas na revisão final. ^d", conf="d"),

    dict(id="B8", title="Dano máximo e economia de vigor", mods="1112, 1384, 2179, 1558", dims=["Dano", "Vigor", "Dificuldade"],
         scope="Propaga para todo combate (jogador e NPCs)",
         what="Teto de dano (`MaxDamage`), custo base de atacar, regeneração de vigor e coeficientes de força e vigor.",
         rows={"type": "params", "mods": ["1112", "1384", "2179", "1558"], "params": ["MaxDamage", "BaseAttackStaminaCost", "StamRegenBase", "StamRegenFromVit", "StamRegenBlockMod", "StamRegenCooldown", "StamRegenMoveMod", "MaxStatToAttackMult", "MinStatToAttackMult", "MaxStatToAttackStaminaCostMult", "StamDamage", "SprintCost", "JumpCostBase", "AimStamCost"]},
         meaning="`MaxDamage` limita todo dano de vida e de vigor de um golpe (200 no jogo). `BaseAttackStaminaCost` é o vigor gasto por ataque; `StamRegen*` define a velocidade e o atraso da recuperação; `MaxStatToAttackMult` e `...StaminaCostMult` ajustam dano e custo por diferença de atributo. ^c (referência)",
         why="Todos concordam em baixar `MaxDamage` para 100: nenhum golpe passa de 100. A partir daí divergem: 1112 quer vigor escasso (custo de ataque 22, regeneração 16, vitalidade quase não ajuda: 0,1); 1558 quer vigor mais fluido (regeneração 25, vitalidade 1,1, atraso 1,25) com custo 20 e saltar/correr mais caros. 2179 e 1384 mexem pouco aqui. ^d",
         effect="`MaxDamage` 100: nenhum golpe tira mais de 100 de uma vez, o que prolonga duelos e reduz mortes súbitas. Custo de ataque 12 → 22: cerca de 80 % mais vigor por golpe, então menos golpes seguidos e mais pausa; com `StamRegenFromVit` 1 → 0,1 o atributo de vitalidade quase não ajuda a recuperar. ^d",
         others="`MaxDamage` é escrito por 7 mods graduados; os quatro daqui concordam em 100, mas no modo Hardcore o 1558 usa 80.",
         verdict="Coerente em `MaxDamage` (100); o resto diverge. O custo do ataque em 22 combinado com regeneração em 16 (1112) pode tornar o jogador lento em brigas contra vários inimigos: testar. ^d", conf="d"),

    dict(id="B9", title="Quanto a habilidade conta para dano e defesa", mods="1384, 2179, 1558", dims=["Dano", "Progressão"],
         scope="Propaga para a curva de poder do jogador e dos NPCs",
         what="Constantes que convertem nível de habilidade e estado do equipamento em dano e defesa.",
         rows={"type": "params", "mods": ["1384", "2179", "1558", "2173"], "params": ["SkillToDmgConstA", "SkillToDefense", "SkillToFencingBase", "ArmorStatusToDefenseCoef", "WeaponStatusToAttackCoef", "ArmorDefenseToAttackingWeaponStatus", "AverageArmorDefenseWeight"]},
         meaning="`SkillToDmgConstA` e `SkillToDefense` são os coeficientes da conta habilidade → dano e habilidade → defesa (quanto cada nível ajuda). `ArmorStatusToDefenseCoef` e `WeaponStatusToAttackCoef` dizem quanto o desgaste de armadura e de arma reduz defesa e ataque. ^d (nomes; fórmula exata não lida)",
         why="1384 sobe o coeficiente de dano (250 → 700): habilidade conta mais para o dano; 1558 o desce (100): conta menos. 2179 aumenta `SkillToDefense` 10x (0,02857 → 0,2857); 1558 o reduz (0,01). Direções opostas. ^c (valores)",
         effect="`SkillToDmgConstA` 700 (1384) contra 100 (1558): um dá a diferença entre iniciante e mestre muito maior no dano, o outro quase a elimina. `SkillToDefense` x10 (2179) torna a habilidade de defesa decisiva; 0,01 (1558) a anula. A mesma partida teria curvas de progressão completamente diferentes. ^d",
         others="Cada parâmetro é escrito só por 3 a 5 mods. `SkillToDefense` aparece nos três com valores opostos.",
         verdict="Contradição profunda e de alto impacto na progressão. Prioridade para a revisão final: decidir a curva desejada (iniciante x mestre) antes de qualquer outra coisa deste grupo. ^d", conf="d"),

    dict(id="B10", title="Estado do equipamento e moral dos NPCs, movimento e armadura", mods="2179", dims=["IA", "Equipamento", "Dificuldade"],
         scope="Propaga para todos os NPCs e para o jogador (peso da armadura)",
         what="Tabelas que definem a vida do equipamento com que os NPCs nascem, a armadura básica do corpo, o ataque desarmado, a moral por evento e o efeito do peso da armadura.",
         rows=[("`social_class.preset_items_health_base` (31 linhas)", "ex.: 0,85", "0,9; mediana x1,06; mínimo x0,67, máximo x1,6"), ("`social_class.preset_items_health_random` (41 linhas)", "ex.: 0,05 / 0,15", "0,1 / 0,2 a 0,5; mediana x2"),
               ("`soul_archetype.body_base_armor` (5)", "1,3 / 2,5 / 1,1", "1,5 / 1,5 / 0,5"), ("`soul_archetype.unarmed_attack_base` (2)", "2,6 / 2,5", "2,2 / 0,5"),
               ("`rpg_movement_type.armor_load_to_speed`", "-0,5 / -1", "-1 / -2 (dobro do efeito do peso)"), ("`rpg_movement_type.armor_load_to_regen`", "0 / 0", "0,1 / 0,25"), ("`rpg_movement_type.stamina_regen`", "0,75", "0,9"),
               ("`morale_change.change` (7)", "ex.: -0,3; -0,1; 0,1; -1", "-0,2; -0,05; 0,05; vazio (a maioria pela metade)"), ("`MoraleForCombat`, `MoraleDecisionReliability`", "-", "0,1; 0,2")],
         meaning="`preset_items_health_*` diz em que estado (0 a 1) o equipamento de cada classe social aparece quando o NPC nasce: aumentar o aleatório deixa os NPCs mais variados (alguns com a arma quase quebrada). `morale_change` é quanto cada evento mexe na coragem do NPC; metade do valor deixa os NPCs mais firmes (menos fugas). ^d",
         why="2179 quer combate 'mais punitivo': NPCs duráveis em média, mas com variação; mais peso da armadura. ^d",
         effect="Roupa e armas dos NPCs variam mais de condição; o peso da armadura reduz a velocidade e a recuperação de vigor (o dobro do jogo). O ataque desarmado dos NPCs (um arquétipo) cai de 2,5 para 0,5: briga limpa com NPC desarmado fica mais fácil. ^d",
         others="Nenhum outro mod do grupo B toca essas tabelas.",
         verdict="Família de mudanças isolada e coerente; é uma das candidatas a aproveitamento seletivo (linha a linha), pois ninguém mais a faz. ^d", conf="d"),

    dict(id="B11", title="Perks e poções de combate reduzidas, com textos atualizados", mods="2179 (35 buffs), 1384 (8), 2173 (2)", dims=["Dano", "Progressão", "Consistência de texto"],
         scope="Propaga para as perks que o jogador possui",
         what="Valores dos buffs de perks e de poções de combate (`buff.params`) e suas durações.",
         rows={"type": "cells", "table": "buff", "column": "params", "mods": ["2179", "1384", "2173"], "keys": None, "limit": 30},
         meaning="`buff.params` guarda a fórmula do efeito: `wat*1.1` multiplica o dano da arma por 1,1; `cli+0.4` soma 0,4 de chance de clinch; `hlh*0.5` multiplica por 0,5 o dano sofrido. `duration` é em segundos. Quanto maior o multiplicador, mais forte a perk. ^c (códigos pelo mod 1009)",
         why="Nerf geral de perks de dano e de bloqueio (de +20 % para +10 %, de +40 % para +10 %) para que a vantagem do jogador não ofusque o combate duro dos outros ajustes. Poções de vigor/arco passam de 600 s para 120-300 s. ^d",
         effect="Perks como Furious, Chain Strike e Cuman Killer perdem metade do bônus de dano; `perk_clinch_master` cai de +0,4 para +0,1. Poções de vigor duram 2 a 5 vezes menos. 2179 atualiza as 36 descrições para os novos números; 1384 não atualiza nenhuma. ^c",
         others="Os três do grupo escrevem `buff`; 2173 e 2179 mexem no mesmo buff `perk_weapon_cruncher` (valores diferentes: +0,05 no 2173).",
         verdict="Direção parecida (nerf de perks); o 2179 é o único consistente em texto. Valores a decidir com o desenho de progressão (B9). ^d", conf="d"),

    dict(id="B12", title="Arco, flechas e alcance", mods="2179, 2035, 1558", dims=["Dano", "IA", "Equilíbrio de armas"],
         scope="Propaga para jogador e NPCs arqueiros",
         what="Dispersão da mira, tempo de carga, dano e tipo de dano das flechas, e alcance do arco.",
         rows={"type": "params", "mods": ["2179", "1558"], "params": ["AimSpreadMax", "AimStamCost", "RangedWpnSelfHarmCoef", "BowChargeDurationMin", "BowPowerToChargeDuration", "AimZoomMax", "AimZoomBase", "AimSpreadSkillDecrease", "AimSpreadMinRatio", "AimPainlessDelay", "RangedWpnMinStrCoef", "RangedWpnPwrToSpeed", "ProjectileMaxBreakProb", "ForcedFireAimSpreadMalus"], "extra": [
             ("Dano das flechas (`ammo.stab_att` para `slash_att`/`smash_att`)", "perfurante 8 a 15", "2035: perfurante 0 a 8,7; cortante 6 a 9,2; contundente 1,9 a 9,1"),
             ("`ammo.power_mod`", "0,85 a 1,1", "2035: 1,15 a 1,64; 2179: 0,5 a 1,5"),
             ("Alcance do arco (`weapon_class`: `attack_distance` / `max_attack_distance`)", "30 / 45", "2035: 99,1 / 150 (3,3x)"),
             ("Entidade da flecha (massa / velocidade)", "0,3 / 60", "2035 (provavelmente inerte): 25,3 / 2666")]},
         meaning="`AimSpreadMax` é o espalhamento do tiro quando o personagem é fraco (15 graus-equivalentes); as constantes de carga (`BowCharge*`) definem quanto o arco precisa ser puxado; `power_mod` multiplica o dano da flecha; `attack_distance` e `max_attack_distance` do arco dizem a que distância a IA e o cálculo de acerto consideram 'em alcance'. ^c (nomes) / ^d (unidades)",
         why="2179: 'arcos e flechas mais rápidos, mais punição se fraco'. 2035: 'revisão completa do sistema de arco'. 1558: menos custo de mirar e mais dispersão máxima (pior para o fraco), efeito contrário ao 2179. ^c",
         effect="2179 reduz a dispersão máxima (tiros mais precisos para o fraco) e acelera a carga. 2035 deixa as flechas cortantes em vez de perfurantes (pior contra placas) e **triplica o alcance**, o que muda a ordem de uma luta de arqueiros (de dentro da emboscada para atirador de longe). ^d",
         others="Cerca de nove mods do grupo C (arco) escrevem as mesmas constantes ocultas; `AimSpreadMax` é escrito por 4 mods (2179, 1558 e dois do grupo C).",
         verdict="Valores contraditórios entre 2179 e 1558; o alcance do 2035 é extremo. Para o arco, a decisão é de design e já existe um módulo planejado (`krs_bow`). ^d", conf="d"),

    dict(id="B13", title="Armas de haste reequilibradas (Polearms Unleashed Lite)", mods="2045", dims=["Equilíbrio de armas", "Economia", "Dificuldade"],
         scope="Local (12 armas), mas muda preço e estoque nas lojas",
         what="Dano por tipo (cortante, perfurante, contundente), defesa, força exigida, durabilidade, preço e peso de 12 armas de haste.",
         rows={"type": "wide", "mod": "2045", "cols": [["melee_weapon", "attack"], ["melee_weapon", "stab_att_mod"], ["melee_weapon", "smash_att_mod"], ["weapon", "defense"], ["weapon", "str_req"], ["weapon", "max_status"], ["pickable_item", "price"], ["pickable_item", "weight"]], "limit": 12},
         meaning="`attack` é o dano-base da arma; os `*_att_mod` são multiplicadores por tipo de golpe (cortante/perfurante/contundente). `defense` é a qualidade do bloqueio com a arma; `str_req`, a força mínima; `max_status`, a durabilidade. `price` é em groschen x10. ^c (nomes) / ^d (unidades de preço)",
         why="A página fala em 'realismo e jogabilidade básica': lanças deixam de ser o melhor jogo; alabardas e martelos ficam distintos entre si; todas têm exigência de força condizente. ^d",
         effect="A maioria das armas perde dano-base (mediana x0,83) mas ganha modificadores por tipo diferentes, e a durabilidade e a defesa mudam em ambas as direções. Os preços sobem em mediana 3x (de 810 até 6000 em alguns casos) e as armas entram nas lojas (30 linhas). Com a habilidade `weapon_large` visível, o jogador vê e treina a habilidade. ^d",
         others="Nenhum outro mod do grupo B mexe nessas linhas; a análise geral mostra sobreposição com mods de arma de outros graus (1563 Karnages Polearm, 2294, 1148).",
         verdict="O melhor trabalho de balanceamento de armas do grupo B. Os preços subidos 3x a 7x são os pontos a rever, e as animações exigem fusão por fragmento (já feita para outros mods). ^d", conf="d"),

    dict(id="B14", title="A economia do reparo (kits, preços e selas)", mods="2173, 1558", dims=["Economia", "Sobrevivência", "Dificuldade"],
         scope="Propaga para reparo, comércio e inventário dos NPCs",
         what="Preço do reparo nas lojas, capacidade e preço dos kits de reparo, durabilidade de selas e kits nos inventários dos NPCs.",
         rows={"type": "params", "mods": ["2173", "1558"], "params": ["RepairKitCapacity", "RepairPriceModif", "RepairKitItemHealthBestLimit", "RepairKitItemHealthDefaultLimit", "RepairKitItemPerkBuffHealthThreshold", "RepairKitMaxSkillCapacityCoef", "DamageToArmorStatusHigherLayers", "SkillXPUseRepairKit"], "extra": [
             ("Kit grande de armadura (preço / peso)", "2000 / 1", "2173: 3000 / 2"), ("Kit pequeno de armadura (preço / peso / eficiência)", "600 / 0,5 / 0,5", "2173: 900 / 1 / 0,2"), ("Kits pequenos nos inventários de NPCs (`amount_random_add`)", "1", "2173: 0"),
             ("Selas de cavalo (`armor.max_status`)", "0 (não gastam)", "2173: 30 a 60 e reparáveis"), ("Perk 'Well maintained' / 'Weapon cruncher'", "15 % / +0,15", "2173: 10 % / +0,05")]},
         meaning="`RepairPriceModif` multiplica o preço de um reparo pago no ferreiro (0,65 no jogo: reparo com desconto; 1 = preço cheio). `RepairKitCapacity` é quanto 'pontos de reparo' um kit contém. Os `RepairKitItemHealth*Limit` dizem até que fração da vida do item o kit pode restaurar (0,1 e 0,9 deixam o kit trabalhar entre 10 % e 90 % da vida). ^c (nomes) / ^d (unidades)",
         why="2173: 'pagar o custo cheio nas lojas e remover kits de inimigos' para que o reparo seja uma decisão (hardcore). 1558: 'kits muito mais duráveis e podem reparar muito mais'. Objetivos opostos. ^c",
         effect="2173: reparo na loja a preço cheio (+54 %), kits 50 % mais caros e mais pesados mas com 3x a capacidade, sem kits grátis nos inimigos: o reparo vira um gasto planejado; a sela passa a gastar. 1558: um kit de 8000 repara quase tudo e `RepairKitItemHealth*` 0 e 0,1 deixam reparar de qualquer estado: reparo quase sem custo. ^d",
         others="Reparo também é escrito por `krs_qol` (módulo do projeto), 883, 1842, 2188, 2340. `RepairPriceModif` é escrito por 5 mods.",
         verdict="O 2173 é coerente como pacote; o 1558 o contradiz. O `krs_qol` do projeto já tem posição própria sobre reparo (decisão do autor). ^d", conf="d"),

    dict(id="B15", title="Catálogo das 56 perks do Perkaholic", mods="1009, 770, 85", dims=["Progressão", "Conteúdo novo", "Dano"],
         scope="Propaga para toda a árvore de perks das habilidades de combate",
         what="56 perks novas (nível 3 a 14) em 7 habilidades e 3 atributos, cada uma com um buff constante.",
         rows={"type": "perkcat", "mod": "1009"},
         meaning="Cada perk tem um nível de habilidade mínimo e liga a um buff `Cpp:Constant` cuja fórmula soma ou multiplica uma característica. Legenda dos códigos no glossário. Uma perk com 'I, II, III' é uma cadeia: a seguinte substitui o buff da anterior (`perk_buff_override`). ^c",
         why="'Mais perks para habilidades que quase não têm': Briga, Arco e Armas de Haste. A maioria dá 5 % a 10 % (poucos efeitos 'ativos'), mantendo o equilíbrio do jogo base. ^c",
         effect="Mais escolhas a cada nível de habilidade, de efeito pequeno (dano +5 %, 5 % menos dano sofrido, +10 % de vigor máximo). Poucas são grandes: Fury Swipes (`asp*2`, velocidade do golpe até 2x quando muito cercado), Diehard (`ibi*2`, sangra 2x mais devagar), Berserker (`bad+0.5`, os inimigos fogem) e Immovable Object (armadura +10 %, mas 20 % mais lento). As perks exclusivas obrigam a escolher uma de duas. ^c",
         others="85 e 770 trazem exatamente as mesmas 56 perks e buffs; o 1009 corrige `rst*1.1` (código inexistente) para `mst*1.1`.",
         verdict="Material valioso para o `krs_perks` (que hoje só tem Riposte e Master Strike). Decidir, na revisão final, quais das 56 perks interessam e se o mod é exigido ou copiado. ^c", conf="c"),

    dict(id="B16", title="XP, teto de nível e progressão (1558)", mods="1558", dims=["Progressão", "Ritmo"],
         scope="Propaga para toda a curva de nível do jogador",
         what="Quanto XP cada ação dá e até que nível se pode chegar.",
         rows={"type": "params", "mods": ["1558"], "params": ["SkillCap", "StatCap", "SkillXPKill", "SkillXPHit", "SkillXPComboHit", "SkillXPBlock", "SkillXPPerfectBlock", "SkillXPRiposte", "StatXPHit", "StatXPComboHit", "StatXPKill", "HunterXPKill", "HorseRidingXPPerDistance", "PickpocketingXP", "StealthAttackMaxXp", "LockPickingStealthXP", "LockPickingSuccessXPMulCoef", "StatXPVitalityPerVault", "StatXPVitalityPerJump", "SpeechXPLevelBase", "VitalityXPLevelBase", "ReadingXpPerHour"], "extra": [
             ("`document_required_skill.skill_xp_gained` (livros, 40 linhas)", "200 / 70 / 350 / 500", "400 / 140 / 700 / 1000 (x2)")]},
         meaning="As constantes de XP definem quanto cada ação acrescenta à barra da habilidade; as `*XPLevelBase` definem a distância entre níveis (dobrada para fala e vitalidade). O teto 40 permite continuar evoluindo depois dos 20 níveis originais. ^c (nomes) / ^d (`SkillCap` 20)",
         why="Karnage: 'Todos os ganhos de XP equilibrados' e 'teto de habilidade 40'. XP de combate e de ações raras (vaulting, cavalo) sobe muito mais do que XP de ações comuns, a favor de quem joga todo tipo de coisa. ^c",
         effect="Progressão muito mais rápida em quase tudo (x3 a x12), compensada em parte pelo teto 40 e pela barra de fala/vitalidade mais longa. Cavalgar 150 contra 12,5 e Hunter 100 contra 15 fazem o jogador subir só por cavalgar e caçar. Livros dão o dobro do XP. ^d",
         others="`ReadingXpPerHour` é escrito por 3 mods e pelo `krs_items` (valor do projeto: 5); vários mods graduados escrevem XP de combate.",
         verdict="Candidato a lista de valores, família a família; o teto 40 e o XP de cavalo/caça são decisões de design, não correções. Coerência com os módulos `krs_*` a decidir. ^d", conf="d"),

    dict(id="B17", title="Carga, reparo, sujeira, facção, preços e inconsciência (1558)", mods="1558", dims=["Sobrevivência", "Economia", "Dificuldade"],
         scope="Propaga para vários sistemas independentes",
         what="Mudanças de constantes que não são de combate nem de XP.",
         rows={"type": "params", "mods": ["1558"], "params": ["BaseInventoryCapacity", "RepairKitCapacity", "ClothDirtyingUpdatePeriod", "FullClothDirtyingOnFullSpeed", "FullClothDirtyingOnZeroSpeed", "ShoeHealthDecrease", "CombatHitUnconsciousDepth", "CombatHitImmortalUnconsciousDepth", "FactionAngrinessDecayBase", "BarterPriceSellRepBuying", "BarterPriceSellRepCoef", "IndulgenceBasePrice", "QuestMoneyRewardScaleConstant", "HorseMountMaxRelativeEncumberance", "HerbGatherSkillToRadius", "PickpocketingDistance", "PickpocketingFailXPMod", "JumpCostBase", "SprintCost"]},
         meaning="`BaseInventoryCapacity` é o peso que Henry carrega sem Força. `ClothDirtying*` controla a velocidade com que a roupa fica suja (9999 quase desliga). `...UnconsciousDepth` é quanto de vida abaixo do mínimo derruba o personagem inconsciente (menor = acorda antes). `FactionAngrinessDecayBase` é a rapidez com que uma facção esquece uma ofensa. ^c (nomes) / ^d (unidades)",
         why="'Mais carga, ficar limpo por muito mais tempo, inconsciência pela metade, kits de reparo mais duráveis, botas desgastam mais devagar' (leia-me). Nota: a sola da bota desgasta 10x MAIS rápido (0,01, contra 0,001), contrário ao que o leia-me diz ('botas desgastam mais devagar'). ^c",
         effect="Henry carrega quase o dobro sem Força; roupa nunca fica suja; a bota gasta 10x mais; o crime é esquecido 6x mais depressa; preços de compra e venda sobem 17 %; o preço de indulgência x2,5. O leia-me e o valor se contradizem em `ShoeHealthDecrease` (provável erro). ^c (contradição) / ^d (efeito)",
         others="`BaseInventoryCapacity` e `StrengthToInventoryCapacity` são escritos por vários mods (651, 883, 1839, 2124...). `ShoeHealthDecrease` é zerado pelo mod 1425 (grau C).",
         verdict="Lista misturada de decisões independentes, com pelo menos um erro provável (sola da bota). Revisar valor por valor com o autor do projeto; nenhum é consequência de outro. ^d", conf="d"),

    dict(id="B18", title="Preços de serviços: banho, quarto, treinadores e cavalos", mods="1105", dims=["Economia"],
         scope="Local (serviços), mas muda quanto dinheiro o jogador precisa em cada fase",
         what="Preços fixos dos serviços e a fórmula do preço dos cavalos.",
         rows=[("Banho, nível 1 a 6 (`dlg_crimeFineAmount` do script)", "10 / 20 / 30 / 40 / 20 / 15", "100 / 200 / 300 / 500 / 250 / 250"), ("Quarto temporário (20 em todas as cidades)", "20", "200 a 500 (Ledetchko 300, Mytinka 500, Rataje/Sasau 400, Talmberg/Uzice 200)"),
               ("Quarto permanente (2000 a 2500)", "2000-2500", "2000 a 6500 (Mytinka 6500)"), ("Treinador, 1º nível (jogo 600)", "600", "300 a 500 conforme a habilidade"), ("Treinador, 2º / 3º / 4º nível (jogo 1800 / 5400 / 16200)", "1800 / 5400 / 16200", "1250-1750 / 4500-7500 / 15000-25000"),
               ("Cavalo", "interpolação entre mínimo e máximo, piso `HorseMinFinalPrice`", "soma² x 6 + 2500, sem piso")],
         meaning="O banho, o quarto e o treinador têm preço fixo em 'groschen x10'. O 'quarto temporário' é a diária; o permanente é a compra. O cavalo é calculado por fórmula a partir dos atributos. ^c (valores) / ^d (unidades)",
         why="Página: 'aumentar os preços dos serviços básicos'. A intenção é tornar o dinheiro mais escasso para o jogador comum. ^c",
         effect="Dormir numa cama de estalagem passa a custar 10 a 25 vezes mais; o banho 10 a 12 vezes. Os treinadores ficam mais baratos no 1º nível e mais caros no 4º. Cavalos de atributos altos podem ficar bem mais caros que no jogo (a fórmula é quadrática). ^d",
         others="Preços também são alterados por 1558, 2173, 2124, 2299 e 2188 (outros graus), cada um em outro ponto.",
         verdict="Mudanças simples de entender, mas feitas com scripts inteiros; o conteúdo dos números é o que interessa. 10x no quarto é um salto grande (Q16). ^d", conf="d"),

    dict(id="B19", title="Camping: dormir fora, tecidos e estoque de lojas", mods="1062", dims=["Sobrevivência", "Economia", "Conteúdo novo"],
         scope="Propaga para dormir, salvar e lojas de tecido",
         what="Qualidade do sono em camas novas (acampamento), itens de camping e o estoque das lojas de pano.",
         rows=[("`sleeping_spot_type` (no jogo)", "exceptional 1 / high 0,7 / medium 0,5 / low 0,3 / ground 0,1", "mantidos; novos: `twenty` 0,2 / `thirtyfive` 0,35 / `fortyfive` 0,45"), ("`shop_type2item.amount` (flemishCloth, 12 linhas)", "3", "1"),
               ("`shop_type2item.shop_type_id` (8 linhas)", "44", "28, 46, 69, 90 (2 linhas cada)"), ("Novo estoque: linho (`linenCloth`)", "-", "6 linhas"), ("Itens entregues ao jogador", "-", "livro 'Camp setting' + guias de chá, leite e cozinha")],
         meaning="A qualidade do sono (0 a 1) define quanto cada hora de sono restaura de vida e vigor. Os tecidos no inventário aumentam o conforto do acampamento: o texto do item diz 'tecidos no inventário aumentam o conforto da cama: linho +; flamengo +'. ^c (valores) / ^d (efeito)",
         why="Dar ao jogador um modo de dormir fora das estalagens e um motivo para carregar pano. ^d",
         effect="Quem carrega pano pode dormir bem (45 % de qualidade) em qualquer lugar; as lojas vendem menos pano flamengo (de 3 para 1) e passam a vender linho. O livro de salvamento do acampamento muda quando se pode salvar. ^d",
         others="`sleeping_spot_type` também é patcheada por 480 Bed Comfort Restored e 1424 Better Sleep Fixed (grau C), que sobem a qualidade das camas do jogo.",
         verdict="Sistema de conteúdo; só entra se o projeto abraçar acampamento. A decisão não é de números. ^d", conf="d"),

    dict(id="B20", title="Itens novos e estoque de lojas", mods="1380, 2045, 2209", dims=["Economia", "Conteúdo novo"],
         scope="Local (itens novos), mas muda o que se vende",
         what="Linhas novas de `shop_type2item` que colocam itens novos à venda, com quantidade e preço.",
         rows=[("1380 Black Items: peças pretas", "-", "17 entradas de loja (amount 1)"), ("2045 PURLE: armas de haste", "-", "30 entradas de loja (amount 1)"), ("2209 Poisonous Enemies patch: capuz e luvas de envenenador", "-", "26 entradas (amount 0)"),
               ("1062 SIM Camping: linho", "-", "6 entradas")],
         meaning="`shop_type2item` liga um tipo de loja a um item, com `amount` (quantidade inicial) e se está ligado por padrão. `amount` 0 significa que o item existe na tabela mas a loja começa sem estoque (provavelmente reservado ao script). ^d",
         why="Fazer o conteúdo novo ser encontrado por compra, não só por saque. ^d",
         effect="Os itens passam a aparecer nas lojas indicadas. As entradas com `amount` 0 (2209) não mudam nada até outro mecanismo as repor. ^d",
         others="Nenhuma sobreposição de linhas entre os quatro.",
         verdict="Sem conflito. Preços e disponibilidade só importam se o conteúdo entrar no projeto. ^d", conf="d"),
]
