"""Grade B review: curated entries of the economy group (1105, 1062), the global rules mod (1558) and the Lua helpers (2318, 2323)."""

MODS = {}

MODS["1062"] = dict(
    name="SIM Camping Mini ML", author="SimranZenov", version="1.5.1.1", subcat="economy",
    status="Lido por inteiro; nada executado",
    purpose="Acampar em qualquer lugar fora da cidade: barraca, fogueira, cama, livro de salvamento, chá, leite e cozinha; tecidos no inventário melhoram o conforto da cama. (Textos do mod.)",
    observed=[
        "Um pak de 37 KB com **54 KB de Lua** (`SIM_Camping.lua`, 1291 linhas) que cria entidades em tempo de execução (cama, fogueira, tenda, cadeira, livro de salvamento, cinzas, colisores); nenhuma é salva pelo jogo (`bSaved_by_game = 0`). ^c",
        "Ao iniciar, o script **põe itens no inventário do jogador**: o 'camping guide' (um livro que monta o acampamento) e variantes para chá, leite e cozinha. ^c",
        "Tabelas com sufixo `sim_camping` (= nome 'SIM Camping'): `item` (5), `pickable_item` (5), `player_item` (5), `questible_item` (4), `ointment_item` (4), `food` (1: chá de camomila), `buff` (2), `perk` (2), `perk_buff` (2) e `shop_type2item` (6 novas, 12 alteradas). ^c",
        "**Substitui a tabela `sleeping_spot_type` inteira (sem sufixo)**: mantém as 5 linhas do jogo e acrescenta 3 qualidades de sono novas (0,2, 0,35 e 0,45). ^c",
        "**Substitui `Scripts/Entities/WH/Bed/Bed.lua`** do jogo: acrescenta as qualidades `ground`, `twenty`, `thirtyfive`, `fortyfive` à função `Bed:GetSleepQuality`. ^c",
        "7 arquivos de ação de interface novos (`sim_ui_onuseevent*.xml`) e textos em 4 idiomas (35 textos novos cada: EN, FR, DE, RU). ^c",
        "Loja: o estoque de 'flemishCloth' cai de 3 para 1 em 12 linhas, 8 linhas mudam de loja e entram 6 linhas de linho. ^c"],
    loads="Manifest sem lista de versões; sufixo `sim_camping` = nome. A tabela `sleeping_spot_type` é inteira. ^c",
    systems=["Dormir fora, salvamento e conforto da cama.", "Comida e bebida de acampamento (chá, leite, cozinhar).", "Itens e estoque de lojas (tecidos).", "Perks de local (campo e cidade) e buffs de localização.", "Interface de uso de itens."],
    newcontent=["5 itens (livro 'Camp setting' e variantes), chá de camomila e entidades de cenário criadas por script; 2 perks e 2 buffs de local (`Cpp:CountrysideLocation` e `Cpp:SettlementLocation`)."],
    stats=["`sleeping_spot_type`: 3 qualidades novas (0,2, 0,35, 0,45) além das 5 do jogo (0,1 a 1,0).", "`shop_type2item.amount` 3 → 1 em 12 linhas (tecido flamengo)."],
    text=["35 textos novos por idioma, 4 idiomas."],
    assets=["Nenhum visual novo além de modelos do jogo; 7 arquivos de ação de interface."],
    params=["`sleeping_quality` 0,2 / 0,35 / 0,45; `shop_type2item.amount`, `shop_type_id`."],
    balance=["B19"],
    snippets=[("A cama substituída", "function Bed:GetSleepQuality()\n  local str = self.Properties.Bed.esSleepQuality;\n+ if str==\"ground\"     then return 4 end\n+ if str==\"twenty\"     then return 5 end\n+ if str==\"thirtyfive\" then return 6 end\n+ if str==\"fortyfive\"  then return 7 end\n  if str==\"low\" then return 2 end ...",
               "A função do jogo mapeia o texto de qualidade da cama para o número da tabela `sleeping_spot_type`. O mod acrescenta quatro nomes (os três novos mais `ground`) e as linhas correspondentes na tabela. Como o arquivo inteiro do jogo é substituído, qualquer outro mod que mexa em `Bed.lua` perde (Q15). ^c")],
    deps=["Nenhuma de arquivo. Em jogo, a pasta/entidade 'Stash' mestre do jogador só é usada se existir."],
    file_overlap=["`Bed.lua` (1 mod no conjunto); `buff`/`perk`/`perk_buff` sem linhas em comum com 85/1009/2011/2173/2179/2209."],
    func_overlap=["Concorre com mods de dormir (480 e 1424 do grupo C) em `sleeping_spot_type`."],
    conflicts=["Tabela `sleeping_spot_type` inteira: sobrepõe 480 Bed Comfort Restored e 1424 Better Sleep; o último na ordem vence."],
    errors=["Substitui `Bed.lua` e `sleeping_spot_type` inteiros ^c.", "O script entrega o guia (e 3 variantes) ao jogador na primeira vez e de novo sempre que o livro some do inventário ^c.", "O cabeçalho de `perk.xml` não declara `autolearnable` ^c: pela regra 5 o campo fica vazio nessas 2 linhas ^n."],
    unique=["Sistema de acampamento completo; novas qualidades de sono.", "Livro de salvamento no acampamento (muda como se salva)."],
    keep=["Possivelmente a ideia das qualidades de sono por tecido, como opção do grupo de dormir/acampar do projeto."],
    reject=["A substituição de `Bed.lua` e da tabela inteira como estão."],
    questions=["Q15 (Bed.lua). O projeto quer um sistema de acampamento? (É conteúdo, não balanceamento.)"],
    rank_note="1º de 2 em Economia de serviços e acampamento",
    action="Conteúdo grande e completo; decidir primeiro se acampamento entra no projeto. Se entrar, empacotar de novo sem substituir `Bed.lua` inteiro.",
    verdict="info", verdict_text="Conteúdo novo",
)

MODS["1105"] = dict(
    name="Service Prices", author="Jabbic", version="1.0 (2020)", subcat="economy",
    status="Lido por inteiro; nada executado",
    purpose="'Aumenta os preços dos serviços básicos (banho, treinadores, camas, cavalos).' (Página do mod.)",
    observed=[
        "Um patch `sequence__service_prices.xml` (6 linhas do script de diálogo dos banhos: o preço do banho) e **3 scripts do jogo substituídos inteiros**: `Horsetraders.lua`, `Sleepover.lua`, `Trainers.lua`. ^c",
        "`Sleepover.lua`: preço do quarto temporário 20 → 200 a 500 (10 a 25 vezes) e do quarto permanente 2000/2500 → 2000 a 6500, por cidade. ^c",
        "`Trainers.lua`: preços dos 4 níveis de treino por habilidade (jogo: 600/1800/5400/16200) passam a 300-500 / 1250-1750 / 4500-7500 / 15000-25000, por habilidade. ^c",
        "`Horsetraders.lua`: a fórmula do preço do cavalo (interpolação entre mínimo e máximo, com piso) é trocada por `soma² x 6 + 2500`, sem o piso `HorseMinFinalPrice`. ^c",
        "Banho: o preço de 6 tipos de serviço sobe 10 a 12,5 vezes (ex.: nível 1: 10 → 100; nível 4: 40 → 500). ^c",
        "Nos três scripts, os comentários do jogo foram apagados (só números e fórmula mudam, mais ruído de diff). ^c"],
    loads="Manifest sem lista de versões. Os três scripts de 2020 diferem do jogo atual só em comentários e nos números alterados, então estão em dia com o 1.9.8 nessas funções. ^c",
    systems=["Preços de serviços (banho, quarto, treinador, cavalo)."],
    newcontent=["Nenhum."],
    stats=["Ver B18."],
    text=["O texto da tabela `sequence` é um script de diálogo (define o valor `dlg_crimeFineAmount` do banho)."], assets=["Nenhum."],
    params=["`Sleepover.places[*].tempRentPrice/permanentRentPrice`, `Trainers.__data__.skills[*].price`, fórmula de `Horsetraders.calcPrices`, `sequence.script` do banho."],
    balance=["B18"],
    snippets=[("Fórmula do cavalo", "-- jogo\nlocal price = math.lerp(horseWithMinStatsPrice, horseWithMaxStatsPrice, average)\nprice = math.max(price, minResultPrice)\nhorseData.price = price * 10\n-- mod\n+ local price = sum   --math.lerp(...)\n+ --price = math.max(price, minResultPrice)\n+ horseData.price = price * price * 6 + 2500",
               "O jogo interpola o preço entre um mínimo e um máximo conforme a média dos atributos do cavalo, com um piso. O mod usa a **soma** dos atributos (não a média) elevada ao quadrado, vezes 6, mais 2500: cavalos bons ficam muito mais caros e o preço não tem mais piso. O resultado depende dos atributos de cada cavalo (Q16). ^c")],
    deps=["Nenhuma."],
    file_overlap=["Substitui `Horsetraders.lua`, `Sleepover.lua`, `Trainers.lua` do jogo; nenhum outro mod do conjunto B toca esses scripts."],
    func_overlap=["Preços de serviços também aparecem em 1558 (`IndulgenceBasePrice`, `BarterPrice*`) e em 2173 (reparo)."],
    conflicts=["Nenhum direto."],
    errors=["Três scripts substituídos para mudar números ^c.", "Fórmula do cavalo sem piso e quadrática ^d.", "Comentários removidos ^c."],
    unique=["Preço de quarto, treinador e cavalo."],
    keep=["Os valores como lista de candidatos (quarto temporário 200-500, treinadores), reescritos como mudanças mínimas de dados, não com scripts inteiros."],
    reject=["A substituição dos três arquivos e a fórmula quadrática de cavalos até simular."],
    questions=["Q16."],
    rank_note="2º de 2 em Economia de serviços e acampamento",
    action="Estudar os números de quarto e treinador; descartar a forma (scripts inteiros).",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["1558"] = dict(
    name="Karnages KCD Essential Fixes 2.0", author="Karnage", version="2.0", subcat="rules",
    status="Lido por inteiro; nada executado",
    purpose="'Revisão total do arquivo RPG_Param do jogo.' (Página do mod.) O leia-me lista: menos balanço de mira, mais capacidade de carga, bloqueio perfeito e riposte muito mais difíceis, mais XP, inconsciência pela metade, teto de habilidade 40, kits de reparo muito mais duráveis, ficar limpo muito mais tempo.",
    observed=[
        "3 patches com sufixo (`Karnages_KCD_Essential_Fixes`, igual ao nome em minúsculas): `rpg_param` (23 novas, 76 alteradas, 2 iguais), `perk_rpg_param_override` (3 novas, 13 alteradas: o modo Hardcore) e `document_required_skill` (40 alteradas: XP dado por cada livro de habilidade x2). ^c",
        "Define teto de habilidade e de atributo em 40 (`SkillCap`, `StatCap`, novas), capacidade de carga base 66 → 125, kits de reparo com `RepairKitCapacity` 200 → 8000 e as chaves de sujeira de roupa em 9999. ^c",
        "Multiplica XP de combate, ladroagem, cavalo e cães por 3 a 12 (ex.: `HorseRidingXPPerDistance` 12,5 → 150; `HunterXPKill` 15 → 100; `SkillXPRiposte` 8 → 50). ^c",
        "Cria **14 chaves de XP de escudo** (`ShieldXP`, `ShieldSkillXP`, `ShieldXPBlock`, `SkillXPShield` ...) que nenhuma lista de constantes do jogo conhece; o leia-me diz 'MAY NOT WORK'. ^c",
        "Linhas de `rpg_param` com o atributo `perk_id` que o cabeçalho não declara (resto de cópia). ^c"],
    loads="Manifest sem lista de versões; sufixo igual ao nome. ^c",
    systems=["IA de combate e dano (`CombatAuto*`, `MaxDamage`, `StatToAttack*`).", "XP de todas as habilidades e atributos.", "Capacidade de carga, reparo, sujeira e desgaste de botas.", "Reputação e barganha, recompensas de missão, ira de facção.", "Inconsciência e dano de queda."],
    newcontent=["Nenhum item; 23 constantes novas (14 delas de XP de escudo, não confirmadas)."],
    stats=["Ver B5, B6, B8, B9 e B16. 99 linhas de `rpg_param`, 16 de Hardcore e 40 de livros."],
    text=["Nenhum."], assets=["Nenhum."],
    params=["`SkillCap` 40, `StatCap` 40, `BaseInventoryCapacity` 66→125, `RepairKitCapacity` 200→8000, `MaxDamage` 200→100, `CombatAutoMaxAttackDelay` 6→1,5."],
    balance=["B5", "B6", "B8", "B9", "B16", "B17"],
    snippets=[("Chaves de escudo sem confirmação", "ShieldXP = 50\nShieldSkillXP = 50\nShieldXPBlock = 50\nSkillXPShield = 50\nSkillXPShieldBlock = 50\nShieldXPPerfectBlock = 50\n... (14 no total)",
               "O jogo tem constantes de XP para outras habilidades (`SkillXPBlock`, `SkillXPPerfectBlock`...), mas nenhuma lista lida contém nenhuma das 14 chaves de escudo. Parecem palpites de nome. Se o motor não as lê, as linhas são inertes e o 'Shield skill XP' do leia-me não acontece. ^c (chaves ausentes) / ^n (efeito)")],
    deps=["Nenhuma."],
    file_overlap=["`rpg_param` e `perk_rpg_param_override` com 1112, 1384, 2179, 2173."],
    func_overlap=["Cruza combate (1112, 1384, 2179), reparo (2173) e XP (vários mods de grau C/D)."],
    conflicts=["Contradiz 2179, 1112, 1384 e 2173 em vários valores (ver B5 a B9 e B14). Quem carrega por último vence."],
    errors=["14 chaves de escudo inexistentes ^c.", "`perk_id` no `rpg_param` ^c.", "Valores extremos: `RepairKitCapacity` 8000, `ClothDirtying*` 9999 (desliga a sujeira) ^c.", "`SkillToDefense` 0,01 (3x menor que o jogo) ^c."],
    unique=["Teto 40 de habilidade/atributo, capacidade de carga, XP de livro x2, XP de cavalo e cão.", "Sujeira de roupa desligada."],
    keep=["Possivelmente os valores de XP e de capacidade, uma família por vez, depois de decidir o ritmo de progressão do projeto."],
    reject=["As 14 chaves de escudo (até confirmar), `RepairKitCapacity` 8000 e a sujeira desligada."],
    questions=["Q8, Q13; qual o ritmo de progressão desejado (teto 40)?"],
    rank_note="1º de 1 em Regras globais: o pacote de parâmetros",
    action="Estudar por família (XP, carga, reparo, combate): é uma lista de candidatos a valores, não um arquivo a copiar.",
    verdict="warn", verdict_text="Investigar / decidir",
)

MODS["2318"] = dict(
    name="Visual Combo Helper", author="r0ughers", version="1.0.0 (31/07/2026)", subcat="lua",
    status="Lido por inteiro; nada executado",
    purpose="Mostra na tela, em ícones, os combos corpo a corpo que o jogador já aprendeu quando uma arma suportada está empunhada. (README.)",
    observed=[
        "Um pak com um script grande (`Scripts/Mods/visualcombohelper.lua`, 2387 linhas), um elemento de interface (`VisualComboHelper.xml` com 6 linhas x 6 ícones por transparência) e um filme `visual_combo_helper.gfx` (2,5 KB). ^c",
        "**Substitui `Libs/UI/Inventory.gfx` do jogo** (209 KB): o script usa o filme do inventário como 'ponte' para ler as perks aprendidas (`UIAction.GetArray('Inventory', ...)`); recarrega o elemento `Inventory` e o esconde (`ReloadElement`, `HideElement`). ^c",
        "O CHANGELOG diz 'informacional apenas: nenhuma mudança de jogo, tempo ou regra'. Nenhuma tabela é alterada. ^c",
        "Consulta periódica (`pollMs = 250`). ^c"],
    loads="Manifest sem lista de versões. Nenhuma tabela. ^c",
    systems=["Interface (HUD) e leitura de perks do inventário."],
    newcontent=["Um elemento de interface novo."],
    stats=["Nenhuma estatística."],
    text=["Usa os tokens de texto do jogo para os nomes dos combos."],
    assets=["`Inventory.gfx` (substituído, 209 KB) e `visual_combo_helper.gfx` (novo)."],
    params=["`VCH.pollMs = 250`, `perkRefreshInterval = 10`."],
    balance=[],
    snippets=[("A ponte do inventário", "pcall(UIAction.ReloadElement, \"Inventory\", -1)\npcall(UIAction.HideElement,  \"Inventory\", -1)\n... UIAction.GetArray, \"Inventory\", ...",
               "Para saber que perks o jogador tem, o mod carrega o filme do inventário (modificado) em segundo plano e lê arrays dele. É engenhoso, mas depende do arquivo de interface do jogo ser substituído e do inventário não ser trocado por outro mod (ex.: 2203, 2204). ^c")],
    deps=["Substitui `Inventory.gfx` do jogo; precisa que o inventário não seja substituído por outro mod."],
    file_overlap=["`Inventory.gfx` pode ser substituído por mods de inventário ordenado de outros graus (2203, 2204, 1719)."],
    func_overlap=["Nenhuma."],
    conflicts=["Com qualquer mod que substitua `Inventory.gfx`."],
    errors=["Interface do jogo substituída ^c; polling de 250 ms ^c."],
    unique=["Único mod de combos na tela."],
    keep=["Nada para balanceamento. Útil como ferramenta de teste de combos."],
    reject=["Não migrar para o mod consolidado (escopo)."],
    questions=["Q10."],
    rank_note="1º de 2 em Auxiliares de interface e de script",
    action="Fora do escopo de balanceamento; manter como ferramenta separada.",
    verdict="info", verdict_text="Fora do escopo",
)

MODS["2323"] = dict(
    name="Alchemy Stash Link", author="não informado no pacote", version="1.0.0 (03/08/2026)", subcat="lua",
    status="Lido por inteiro; nada executado",
    purpose="Liga os baús mestres do jogador (quartos de estalagem, cama de Rataje, baús de casa, estoques de acampamento) e o inventário do cavalo a qualquer bancada de alquimia usada, para usar os ingredientes de lá. (Página do mod.)",
    observed=[
        "Um script (`alchemy_stash_link.lua`, 520 linhas) em `Scripts/Startup`, duplicado solto na raiz do mod, e um `config.lua` solto (3 opções) que **o pak não usa** (a configuração fica dentro do script). ^c",
        "Ao usar a mesa, o script move os ingredientes dos baús e do cavalo para o inventário do jogador e os devolve ao fechar (`MoveItemOfClass`). Cria uma entidade 'stash proxy' temporária (`ASL_TempMasterStash`, não salva). ^c",
        "Detecta ingredientes por uma lista de ~40 GUIDs e, se falhar, por **nome**: qualquer item cujo nome contenha 'herb', 'sage', 'mint', 'mushroom', 'feather', 'tooth', 'weed' etc. ^c",
        "Deixa **comandos de console de teste**: `alchemy_give_all` (dá 10 de cada erva e libera receitas, via `cheat_add_item` e `cheat_unlock_recipes` do mod Cheat) e `alchemy_check`/`alchemy_status`. ^c",
        "Um temporizador de 1 s ('safeAutoHookLoop') tenta ligar o gancho na mesa até conseguir. ^c"],
    loads="Manifest sem lista de versões; nenhuma tabela. ^c",
    systems=["Alquimia (origem dos ingredientes) e inventários (baús, cavalo)."],
    newcontent=["3 comandos de console."],
    stats=["Nenhuma."], text=["Nenhum."], assets=["Nenhum."],
    params=["`Config.PullFromStash`, `PullFromHorse`, `Verbose` (todos verdadeiros)."],
    balance=[],
    snippets=[("Comando de teste que fica no jogo", "System.AddCCommand(\"alchemy_give_all\", \"AlchemyStashLink:GiveAllTestingItems()\",\n  \"Spawns 10 of all alchemy ingredients (exact GUIDs) and unlocks recipes\")\n... System.ExecuteCommand(\"cheat_add_item id:\" .. guid .. \" amount:10\")",
               "É um atalho de teste do autor que continua no mod. Só funciona se o mod Cheat (106) estiver presente (`cheat_add_item` é comando dele); sem o Cheat, falha sem efeito. Com o Cheat, qualquer um que digite o comando no console ganha ingredientes e receitas. Para um mod consolidado, deve ser **removido**. ^c")],
    deps=["Para os comandos de teste, o mod Cheat (106, em quarentena). A função principal não depende de nada."],
    file_overlap=["Nenhum arquivo do jogo substituído."],
    func_overlap=["Concorre (em ideia) com mods de organização de inventário; não há mod igual neste conjunto."],
    conflicts=["Mods que movem ingredientes ao mesmo tempo (nenhum visto)."],
    errors=["Comandos de teste ^c.", "Detecção por nome pode mover itens que não são ingredientes ('mushroom', 'feather', 'tooth') ^c.", "`config.lua` solto não usado ^c.", "Laço de temporizador de 1 s ^c."],
    unique=["Único mod do conjunto sobre origem dos ingredientes."],
    keep=["Possivelmente a ideia como mod de qualidade de vida (`krs_qol`), reescrita sem comandos de teste."],
    reject=["`alchemy_give_all` e a detecção por nome."],
    questions=["Q17."],
    rank_note="2º de 2 em Auxiliares de interface e de script",
    action="Candidato a qualidade de vida; reescrever sem os comandos de teste.",
    verdict="info", verdict_text="Candidato a QoL",
)
